In [34]:
#overlap Pfenning peaks
import pandas as pd
import os
import gzip

# Assuming df_final is already loaded and has the correct columns
df_peak = pd.read_csv('indexing/SNP_haploreg_annotated_20231204.csv', index_col=0)

# Function to check if a position is within a peak
def is_within_peak(chrom, pos, peak_df):
    # Ensure the chromosome is a string because it can be 'X', 'Y', or a number
    chrom = str(chrom)
    # Convert position to integer to perform numeric comparisons
    pos = int(pos)
    #if chrom == 11 and pos == 
    # Filter peak_df for rows where the variant is in the chromosome
    # Ensure peak_df['chrom'] is string type to match with 'chrom'
    chrom_peaks = peak_df[peak_df['chrom'].astype(str) == chrom]
    
    # Check if 'pos' is within any of the peak ranges
    # Start and end positions are converted to integers for comparison
    within_peak = chrom_peaks[(chrom_peaks['start'].astype(int) <= pos) & (chrom_peaks['end'].astype(int) >= pos)]
    
    # If 'within_peak' is not empty, return 1, else return 0
    return 1 if not within_peak.empty else 0

# Directory containing the peak and bed files
directory = "../atac/all_open_chromatin_peaks/THP1_4hrs_differential_fdr005"

# Loop through the files in the directory
for filename in os.listdir(directory):
    if filename.endswith(".narrowPeak.gz") or filename.endswith(".bed"):
        # Construct file path
        file_path = os.path.join(directory, filename)
        
        # Read the file into a DataFrame
        if filename.endswith(".narrowPeak.gz"):
            with gzip.open(file_path, 'rt') as f:
                peaks_df = pd.read_csv(f, sep='\t', header=None, usecols=[0, 1, 2])
        else:  # .bed file
            peaks_df = pd.read_csv(file_path, sep='\t', header=None, usecols=[0, 1, 2])
        
        # Rename columns for consistency
        peaks_df.columns = ['chrom', 'start', 'end']
        
        # Remove 'chr' prefix if present
        peaks_df['chrom'] = peaks_df['chrom'].str.replace('chr', '')

        # Column name derived from the file name
        column_name = filename.split('.')[0]
        
        # Annotate variants in df_peak with peak information
        df_peak[column_name] = df_peak.apply(
            lambda row: is_within_peak(row['chr'], row['pos_hg38'], peaks_df), axis=1
        )

# Save the annotated DataFrame to a CSV file
df_peak.to_csv('indexing/variants_peak_annotation_THP1FourHrsDifferential_20240117.csv')

In [33]:
df_peak

,Type,RSID,Contributor,nearest_gene,rsID,chr,pos_hg38,r2,D',is_query_snp,...,dbSNP_functional_annotation,query_snp_rsid,Promoter_histone_marks,Enhancer_histone_marks,snp_original,snp_original_haploreghg38,SNP_ID,IFNB4_vs_Naive_IHW,IFNG4_vs_Naive_IHW,LPSIFNG4_vs_Naive_IHW
MPRA_Seq_ID,,,,,,,,,,,,,,,,,,,,,
alt:cg03073402:SNPCENTER:chr19:42927676:C:G:42927563:42927789:42927676,AD,cg03073402,Bertram,LIPE,cg03073402,19,42423524,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,42927676,False,SNP_0,0,0,1
alt:cg03169557:SNPCENTER:chr16:89598950:C:G:89598837:89599063:89598950,AD,cg03169557,Bertram,SPG7,cg03169557,16,89532542,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,89598950,False,SNP_1,0,0,0
alt:cg05030077:SNPCENTER:chr16:2255199:C:G:2255086:2255312:2255199,AD,cg05030077,Bertram,MLST8,cg05030077,16,2205198,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2255199,False,SNP_2,0,0,1
alt:cg05066959:SNPCENTER:chr8:41519308:C:G:41519195:41519421:41519308,AD,cg05066959,Bertram,ANK1,cg05066959,8,41661790,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,41519308,False,SNP_3,0,0,0
alt:cg05228284:SNPCENTER:chr19:2720847:C:G:2720734:2720960:2720847,AD,cg05228284,Bertram,DIRAS1,cg05228284,19,2720849,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2720847,False,SNP_4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
alt:rs114790291:PEAKCENTER:chr16:89365227:G:C:89365046:89365460:89365246,AD,rs114790291,Tanzi,ANKRD11,rs114790291,16,89365227,1.0,1.0,1.0,...,INT,rs114790291,"ESDR, SKIN","ESC, ESDR, LNG, IPSC, FAT, STRM, BRST, BLD, MU...",89365227,True,SNP_104,0,0,0
alt:rs114953660:PEAKCENTER:chr3:132660097:C:G:132659568:132660945:132660107,AD,rs114953660,Tanzi,UBA5,rs114953660,3,132660097,1.0,1.0,1.0,...,U5;INT,rs114953660,"ESC, ESDR, LNG, IPSC, FAT, STRM, BRST, BLD, MU...",NaN,132660097,True,SNP_105,0,0,0
alt:rs115155629:SNPCENTER:chr6:134550983:T:C:134550870:134551096:134550983,AD,rs115155629,Tanzi,LINC03002,rs115155629,6,134550983,1.0,1.0,1.0,...,.,rs115155629,"MUS, LNG","ESC, ESDR, LNG, IPSC, FAT, STRM, BRST, SKIN, L...",134550983,True,SNP_106,0,0,0
alt:rs115177445:SNPCENTER:chr2:113083790:G:A:113083677:113083903:113083790,AD,rs115177445,Tanzi,IL1F10,rs115177445,2,113083790,1.0,1.0,1.0,...,.,rs115177445,NaN,BLD,113083790,True,SNP_107,0,0,0
alt:rs115361688:SNPCENTER:chr2:113083166:C:T:113083053:113083279:113083166,AD,rs115361688,Tanzi,IL1F10,rs115361688,2,113083166,1.0,1.0,1.0,...,.,rs115361688,NaN,BLD,113083166,True,SNP_108,0,0,0

In [35]:
import pandas as pd
df_peak = pd.read_csv('indexing/variants_peak_annotation_THP1FourHrsDifferential_20240117.csv',index_col=0)

In [36]:
df_peak[df_peak["IFNB4_vs_Naive_IHW"] == 1]

,Type,RSID,Contributor,nearest_gene,rsID,chr,pos_hg38,r2,D',is_query_snp,...,dbSNP_functional_annotation,query_snp_rsid,Promoter_histone_marks,Enhancer_histone_marks,snp_original,snp_original_haploreghg38,SNP_ID,IFNB4_vs_Naive_IHW,IFNG4_vs_Naive_IHW,LPSIFNG4_vs_Naive_IHW
MPRA_Seq_ID,,,,,,,,,,,,,,,,,,,,,
alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019088,AD,rs636317,Pfenning,MS4A4A,rs636317,11,60251677,1.0,1.0,1.0,...,.,rs636317,BLD,"BLD, OVRY, VAS",60019150,False,SNP_556,1,1,1
alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019210,AD,rs636317,Pfenning,MS4A4A,rs636317,11,60251677,1.0,1.0,1.0,...,.,rs636317,BLD,"BLD, OVRY, VAS",60019150,False,SNP_557,1,1,1
alt:rs636341:PEAKCENTER:chr11:60019161:A:C:60018954:60020211:60019088,AD,rs636341,Pfenning,MS4A4A,rs636341,11,60251688,1.0,1.0,1.0,...,.,rs636341,BLD,"BLD, OVRY, VAS",60019161,False,SNP_558,1,1,1
alt:rs636341:PEAKCENTER:chr11:60019161:A:C:60018954:60020211:60019210,AD,rs636341,Pfenning,MS4A4A,rs636341,11,60251688,1.0,1.0,1.0,...,.,rs636341,BLD,"BLD, OVRY, VAS",60019161,False,SNP_559,1,1,1
alt:rs672399:PEAKCENTER:chr11:60020112:T:G:60018954:60020211:60020089,AD,rs672399,Pfenning,MS4A4A,rs672399,11,60252639,1.0,1.0,1.0,...,.,rs672399,BLD,"BLD, SKIN, LIV, ADRL, VAS",60020112,False,SNP_574,1,1,1

In [37]:
df_peak[df_peak["IFNG4_vs_Naive_IHW"] == 1]

,Type,RSID,Contributor,nearest_gene,rsID,chr,pos_hg38,r2,D',is_query_snp,...,dbSNP_functional_annotation,query_snp_rsid,Promoter_histone_marks,Enhancer_histone_marks,snp_original,snp_original_haploreghg38,SNP_ID,IFNB4_vs_Naive_IHW,IFNG4_vs_Naive_IHW,LPSIFNG4_vs_Naive_IHW
MPRA_Seq_ID,,,,,,,,,,,,,,,,,,,,,
alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019088,AD,rs636317,Pfenning,MS4A4A,rs636317,11,60251677,1.0,1.0,1.0,...,.,rs636317,BLD,"BLD, OVRY, VAS",60019150,False,SNP_556,1,1,1
alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019210,AD,rs636317,Pfenning,MS4A4A,rs636317,11,60251677,1.0,1.0,1.0,...,.,rs636317,BLD,"BLD, OVRY, VAS",60019150,False,SNP_557,1,1,1
alt:rs636341:PEAKCENTER:chr11:60019161:A:C:60018954:60020211:60019088,AD,rs636341,Pfenning,MS4A4A,rs636341,11,60251688,1.0,1.0,1.0,...,.,rs636341,BLD,"BLD, OVRY, VAS",60019161,False,SNP_558,1,1,1
alt:rs636341:PEAKCENTER:chr11:60019161:A:C:60018954:60020211:60019210,AD,rs636341,Pfenning,MS4A4A,rs636341,11,60251688,1.0,1.0,1.0,...,.,rs636341,BLD,"BLD, OVRY, VAS",60019161,False,SNP_559,1,1,1
alt:rs672399:PEAKCENTER:chr11:60020112:T:G:60018954:60020211:60020089,AD,rs672399,Pfenning,MS4A4A,rs672399,11,60252639,1.0,1.0,1.0,...,.,rs672399,BLD,"BLD, SKIN, LIV, ADRL, VAS",60020112,False,SNP_574,1,1,1

In [39]:
comparative_lps = pd.read_csv('20240129_comparative_THP1_LPSIFNGvsNaive_interaction.csv',index_col=0)
comparative_lps.loc[df_peak[df_peak["LPSIFNG4_vs_Naive_IHW"] == 1].index].sort_values('fdr')

,statistic,pval,fdr,df.test,df.dna,df.rna.full,df.rna.red,logFC
MPRA_Seq_ID,,,,,,,,
alt:rs549746751:PEAKCENTER:chr19:12736940:G:A:12736825:12737331:12737003,18.481551,0.000017,0.005821,1,43,5,4,0.213590
alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019088,16.315304,0.000054,0.010919,1,43,5,4,0.156822
alt:rs10401439:SNPCENTER:chr19:45817522:C:T:45817409:45817635:45817522,10.349352,0.001295,0.101424,1,43,5,4,-0.202689
alt:rs653765:PEAKCENTER:chr15:59042012:T:G:59040961:59042514:59041984,6.248259,0.012432,0.249781,1,43,5,4,0.174232
alt:rs6464547:PEAKCENTER:chr7:143386568:A:T:143386295:143386795:143386545,5.616560,0.017792,0.297966,1,43,5,4,-0.110720
...,...,...,...,...,...,...,...,...
alt:rs9270922:PEAKCENTER:chr6:32572388:T:A:32572337:32572679:32572461,0.003222,0.954737,0.985317,1,43,5,4,0.003602
alt:rs3826327:PEAKCENTER:chr17:75271437:C:T:75270300:75271666:75271337,0.002570,0.959567,0.985317,1,43,5,4,0.004983
alt:rs9270920:PEAKCENTER:chr6:32572322:C:T:32571733:32572743:32572301,0.001937,0.964893,0.986215,1,43,5,4,-0.002383
alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019210,0.001069,0.973919,0.987500,1,43,5,4,0.001320
alt:rs514049:SNPCENTER:chr15:59042363:C:A:59040961:59042514:59042268,-0.000200,1.000000,1.000000,1,43,5,4,-0.000681

In [10]:
comparative_lps = pd.read_csv('allele_differences/HMC3/20240105_comparative_HMC3_LPSIFNG_allele.csv',index_col=0)
comparative_lps.loc[df_peak[df_peak["LPSIFNG4_vs_Naive_IHW"] == 1].index].sort_values('fdr')#.loc['alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019088']

,statistic,pval,fdr,df.test,df.dna,df.rna.full,df.rna.red,logFC
MPRA_Seq_ID,,,,,,,,
alt:rs7924433:PEAKCENTER:chr11:60334375:C:G:60334025:60334525:60334275,17.616632,0.000027,0.001772,1,34,5,4,-0.386408
alt:rs3826327:PEAKCENTER:chr17:75271437:C:T:75270300:75271666:75271337,13.994945,0.000183,0.006409,1,34,5,4,-0.507810
alt:rs67141839:PEAKCENTER:chr6:32572576:GGACAT:G:32572337:32572679:32572652,10.798854,0.001016,0.024007,1,34,5,4,0.361718
alt:rs184094141:PEAKCENTER:chr6:43454798:G:A:43454560:43454887:43454723,7.688153,0.005558,0.076721,1,34,5,4,-0.260063
alt:rs653765:PEAKCENTER:chr15:59042012:T:C:59040961:59042514:59041984,6.410803,0.011343,0.114410,1,34,5,4,-0.340089
...,...,...,...,...,...,...,...,...
alt:rs3809716:SNPCENTER:chr17:75271750:G:C:75270249:75271959:75271843,0.002736,0.958286,0.989849,1,34,5,4,0.006121
alt:rs653765:PEAKCENTER:chr15:59042012:T:C:59040961:59042514:59042091,0.002092,0.963515,0.989849,1,34,5,4,-0.007006
alt:rs3809715:PEAKCENTER:chr17:75271453:A:C:75270241:75271699:75271532,0.000267,0.986970,0.993924,1,34,5,4,-0.001710
alt:rs9270919:PEAKCENTER:chr6:32572305:G:T:32571733:32572743:32572301,0.000032,0.995479,0.997830,1,34,5,4,0.000518
alt:rs2927438:SNPCENTER:chr19:44738850:G:A:44738683:44739183:44738933,-0.000093,1.000000,1.000000,1,34,5,4,0.000063

In [5]:
comparative_lps = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/allele_differences/THP1_Macrophages/20240105_comparative_THP1_LPSIFNG_allele.csv',index_col=0)
comparative_lps.loc[df_peak[df_peak["LPSIFNG4_vs_Naive_IHW"] == 1].index].sort_values('fdr').loc['alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019088']

statistic       1.333343
pval            0.248211
fdr             0.539076
df.test         1.000000
df.dna         35.000000
df.rna.full     5.000000
df.rna.red      4.000000
logFC          -0.053293
Name: alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019088, dtype: float64

In [19]:
import pandas as pd
pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/indexing/SNP_haploreg_annotated_20231204.csv',index_col=0).columns

Index(['Type', 'RSID', 'Contributor', 'nearest_gene', 'rsID', 'chr',
       'pos_hg38', 'r2', 'D'', 'is_query_snp', 'ref', 'alt', 'AFR', 'AMR',
       'ASN', 'EUR', 'GERP_cons', 'SiPhy_cons', 'Chromatin_States',
       'Chromatin_States_Imputed', 'Chromatin_Marks', 'DNAse', 'Proteins',
       'eQTL', 'gwas', 'grasp', 'Motifs', 'GENCODE_id', 'GENCODE_name',
       'GENCODE_direction', 'GENCODE_distance', 'RefSeq_id', 'RefSeq_name',
       'RefSeq_direction', 'RefSeq_distance', 'dbSNP_functional_annotation',
       'query_snp_rsid', 'Promoter_histone_marks', 'Enhancer_histone_marks',
       'snp_original', 'snp_original_haploreghg38', 'SNP_ID'],
      dtype='object')

In [25]:
import pandas as pd
def get_significant_interaction(interaction_file):
    df = pd.read_csv(interaction_file,index_col=0)
    df = df[df["fdr"]<=0.05]
    df["Comparison"] = interaction_file[21:-16]
    return df

df=pd.DataFrame()
for i in ['20240129_comparative_HMC3_IFNBvsNaive_interaction.csv',
          '20240129_comparative_HMC3_IFNGvsNaive_interaction.csv',
          '20240129_comparative_HMC3_LPSIFNGvsIFNG_interaction.csv',
          '20240129_comparative_HMC3_LPSIFNGvsNaive_interaction.csv',
          '20240129_comparative_THP1_IFNBvsNaive_interaction.csv',
          '20240129_comparative_THP1_IFNGvsNaive_interaction.csv',
          '20240129_comparative_THP1_LPSIFNGvsIFNG_interaction.csv',
          '20240129_comparative_THP1_LPSIFNGvsNaive_interaction.csv']:
    df = pd.concat([df,get_significant_interaction(i)])

df_haploreg = pd.read_csv('indexing/SNP_haploreg_annotated_20231204.csv',index_col=0)
pd.merge(df_haploreg,df,left_index=True,right_index=True).sort_index().to_csv("20240205_THP1HMC3_stimulation_specific_haploreg_annotated.csv")

In [24]:
import pandas as pd
df = pd.read_csv("enhancer_activities_differential/20240626_comparative_THP1_LPSIFNGvsNaive_DifferentialEnhancer.csv",index_col=0)
#df_index = pd.read_csv("indexing/SNP_haploreg_annotated_index_20240818_curated_annotated.csv",index_col=0)
#df = pd.merge(df,df_index,left_index=True,right_index=True)
df_ref_alt = pd.read_csv("indexing/ALT_REF_LookUpTable_filtered_amended_20231117.csv",index_col=0)
df_ref_alt.columns = ["ref_enhancer_id"]
#df = pd.merge(df,df_ref_alt,left_index=True,right_index=True)
#df = df.set_index("ref_enhancer_id")
df_alt = df[~df.index.str.contains('REF')]
df_ref = df[df.index.str.contains('REF')]
df_ref.index = df_ref_alt.loc[df_ref.index.str.slice(4)]['ref_enhancer_id']
df = pd.concat([df_ref,df_alt])

df_seq = pd.read_csv("indexing/MPRA3_Contributor_20231108_unique_GeneName_BarcodeEnhancerPair.csv",index_col="enhancer_id")
df_seq = df_seq[~df_seq.index.duplicated(keep='first')][['enhancer_seq']]


df_index = pd.merge(df,df_seq[["enhancer_seq"]],left_index = True,right_index=True)
df_index_sorted = df_index.sort_values(by='fdr').drop_duplicates('enhancer_seq')

def df_to_fasta(df, column_name, file_name):
    with open(file_name, 'w') as f:
        for name, row in df.iterrows():
            f.write(f'>{name}\n{row[column_name]}\n')

# Call the function to write the DataFrame to a FASTA file
df_to_fasta(df_index_sorted[(df_index_sorted['fdr']<=0.05)&(df_index_sorted['logFC']<0)], 
            'enhancer_seq', '20240824_MPRA_LPSIFNG_NAIVE_fdr005_NeglogFC_sig.fasta')#

# Call the function to write the DataFrame to a FASTA file
df_to_fasta(df_index_sorted[(df_index_sorted['fdr']<=0.05)&(df_index_sorted['logFC']>0)], 
            'enhancer_seq', '20240824_MPRA_LPSIFNG_NAIVE_fdr005_PoslogFC_sig.fasta')#

# Call the function to write the DataFrame to a FASTA file
df_to_fasta(df_index_sorted[(df_index_sorted['fdr']<=0.05)], 
            'enhancer_seq', '20240824_MPRA_LPSIFNG_NAIVE_fdr005_AlllogFC_sig.fasta')#

def df_to_fasta(df, column_name, file_name):
    with open(file_name, 'w') as f:
        for name, row in df.iterrows():
            f.write(f'>{name}\n{row[column_name]}\n')

# Call the function to write the DataFrame to a FASTA file
df_to_fasta(df_index_sorted[df_index_sorted['fdr']>0.05], 'enhancer_seq', '20240824_MPRA_LPSIFNG_NAIVE_fdr005_notsig.fasta')

import pandas as pd
df = pd.read_csv("enhancer_activities_differential/20240626_comparative_THP1_IFNGvsNaive_DifferentialEnhancer.csv",index_col=0)
#df_index = pd.read_csv("indexing/SNP_haploreg_annotated_index_20240818_curated_annotated.csv",index_col=0)
#df = pd.merge(df,df_index,left_index=True,right_index=True)
df_ref_alt = pd.read_csv("indexing/ALT_REF_LookUpTable_filtered_amended_20231117.csv",index_col=0)
df_ref_alt.columns = ["ref_enhancer_id"]
#df = pd.merge(df,df_ref_alt,left_index=True,right_index=True)
#df = df.set_index("ref_enhancer_id")
df_alt = df[~df.index.str.contains('REF')]
df_ref = df[df.index.str.contains('REF')]
df_ref.index = df_ref_alt.loc[df_ref.index.str.slice(4)]['ref_enhancer_id']
df = pd.concat([df_ref,df_alt])

df_seq = pd.read_csv("indexing/MPRA3_Contributor_20231108_unique_GeneName_BarcodeEnhancerPair.csv",index_col="enhancer_id")
df_seq = df_seq[~df_seq.index.duplicated(keep='first')][['enhancer_seq']]


df_index = pd.merge(df,df_seq[["enhancer_seq"]],left_index = True,right_index=True)
df_index_sorted = df_index.sort_values(by='fdr').drop_duplicates('enhancer_seq')

def df_to_fasta(df, column_name, file_name):
    with open(file_name, 'w') as f:
        for name, row in df.iterrows():
            f.write(f'>{name}\n{row[column_name]}\n')

# Call the function to write the DataFrame to a FASTA file
df_to_fasta(df_index_sorted[(df_index_sorted['fdr']<=0.05)], #&(df_index_sorted['logFC']<0)
            'enhancer_seq', '20240824_MPRA_IFNG_NAIVE_fdr005_sig.fasta')#
def df_to_fasta(df, column_name, file_name):
    with open(file_name, 'w') as f:
        for name, row in df.iterrows():
            f.write(f'>{name}\n{row[column_name]}\n')

# Call the function to write the DataFrame to a FASTA file
df_to_fasta(df_index_sorted[df_index_sorted['fdr']>0.05], 'enhancer_seq', '20240824_MPRA_IFNG_NAIVE_fdr005_notsig.fasta')

import pandas as pd
df = pd.read_csv("enhancer_activities_differential/20240626_comparative_THP1_IFNBvsNaive_DifferentialEnhancer.csv",index_col=0)
#df_index = pd.read_csv("indexing/SNP_haploreg_annotated_index_20240818_curated_annotated.csv",index_col=0)
#df = pd.merge(df,df_index,left_index=True,right_index=True)
df_ref_alt = pd.read_csv("indexing/ALT_REF_LookUpTable_filtered_amended_20231117.csv",index_col=0)
df_ref_alt.columns = ["ref_enhancer_id"]
#df = pd.merge(df,df_ref_alt,left_index=True,right_index=True)
#df = df.set_index("ref_enhancer_id")
df_alt = df[~df.index.str.contains('REF')]
df_ref = df[df.index.str.contains('REF')]
df_ref.index = df_ref_alt.loc[df_ref.index.str.slice(4)]['ref_enhancer_id']
df = pd.concat([df_ref,df_alt])

df_seq = pd.read_csv("indexing/MPRA3_Contributor_20231108_unique_GeneName_BarcodeEnhancerPair.csv",index_col="enhancer_id")
df_seq = df_seq[~df_seq.index.duplicated(keep='first')][['enhancer_seq']]


df_index = pd.merge(df,df_seq[["enhancer_seq"]],left_index = True,right_index=True)
df_index_sorted = df_index.sort_values(by='fdr').drop_duplicates('enhancer_seq')

def df_to_fasta(df, column_name, file_name):
    with open(file_name, 'w') as f:
        for name, row in df.iterrows():
            f.write(f'>{name}\n{row[column_name]}\n')

# Call the function to write the DataFrame to a FASTA file
df_to_fasta(df_index_sorted[(df_index_sorted['fdr']<=0.05)], #&(df_index_sorted['logFC']<0)
            'enhancer_seq', '20240824_MPRA_IFNB_NAIVE_fdr005_sig.fasta')#
def df_to_fasta(df, column_name, file_name):
    with open(file_name, 'w') as f:
        for name, row in df.iterrows():
            f.write(f'>{name}\n{row[column_name]}\n')

# Call the function to write the DataFrame to a FASTA file
df_to_fasta(df_index_sorted[df_index_sorted['fdr']>0.05], 'enhancer_seq', '20240824_MPRA_IFNB_NAIVE_fdr005_notsig.fasta')