In [2]:
import pandas as pd

In [3]:
df_naive = pd.read_csv("/media/zihengc/T7/mpra3_lib_analysis/allele_differences_withoutcontrol/20240817_allele_only_for_plotting/annotated_20240813_comparative_THP1Macrophage_alleleOnly.csv",index_col=0)
df_naive

,statistic,pval,fdr,df.test,df.dna,df.rna.full,df.rna.red,logFC,logFC_converted,RSID,...,ML_majorminor_diff_genomic_Mouse_Cortex_AgeC-model,ML_majorminor_diff_genomic_Mouse_Striatum_AgeB,ML_majorminor_diff_genomic_Mouse_Striatum_AgeC,ML_majorminor_diff_genomic_THP1_IFNB-Calvin,ML_majorminor_diff_genomic_THP1_IFNG-Calvin,ML_majorminor_diff_genomic_THP1_LPSIFNG-Calvin,ML_majorminor_diff_genomic_THP1_Naive-Calvin,ML_majorminor_diff_genomic_THP1_monocyte0729,ML_majorminor_diff_genomic_WTC11_IFNB,ML_majorminor_diff_genomic_WTC11_resting
alt:cg03073402:SNPCENTER:chr19:42927676:C:G:42927563:42927789:42927676,2.518187,1.125399e-01,1.983951e-01,1,53,6,5,0.037138,0.037138,cg03073402,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:cg03169557:SNPCENTER:chr16:89598950:C:G:89598837:89599063:89598950,29.225528,6.442478e-08,5.922923e-07,1,53,6,5,-0.132102,-0.132102,cg03169557,...,0.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:cg05030077:SNPCENTER:chr16:2255199:C:G:2255086:2255312:2255199,13.473679,2.419334e-04,1.076680e-03,1,53,6,5,-0.086250,-0.086250,cg05030077,...,NaN,NaN,NaN,0.95,NaN,NaN,0.64,NaN,NaN,NaN
alt:cg05066959:SNPCENTER:chr8:41519308:C:G:41519195:41519421:41519308,7.820592,5.165429e-03,1.560580e-02,1,53,6,5,-0.069255,-0.069255,cg05066959,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:cg05228284:SNPCENTER:chr19:2720847:C:G:2720734:2720960:2720847,7.053155,7.912576e-03,2.255084e-02,1,53,6,5,0.100701,0.100701,cg05228284,...,NaN,0.69,0.77,NaN,1.18,NaN,NaN,1.07,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
alt:rs9478143:PEAKCENTER:chr6:150862035:A:G:150861632:150862271:150862051,1.662881,1.972148e-01,3.011048e-01,1,53,6,5,-0.027981,-0.027981,rs9478143,...,-1.23,-1.07,-1.07,NaN,NaN,NaN,NaN,-0.51,NaN,NaN
alt:rs953471:PEAKCENTER:chr9:124221903:G:A:124221758:124221963:124221854,8.550327,3.454602e-03,1.102121e-02,1,53,6,5,0.057097,0.057097,rs953471,...,2.18,2.25,2.20,0.95,1.59,1.30,0.95,0.72,1.61,1.87
alt:rs965034941:SNPCENTER:chr19:1999195:CCA:C:1999082:1999308:1999195,0.882110,3.476245e-01,4.770769e-01,1,53,6,5,-0.022522,-0.022522,rs965034941,...,NaN,NaN,NaN,-0.82,NaN,1.27,-0.58,-0.86,NaN,-0.79
alt:rs983392:PEAKCENTER:chr11:59923508:A:G:59923333:59923833:59923583,1.199203,2.734811e-01,3.936470e-01,1,53,6,5,0.028273,0.028273,rs983392,...,NaN,NaN,NaN,NaN,1.14,NaN,NaN,NaN,0.81,NaN
alt:rs9912783:PEAKCENTER:chr17:61522705:C:T:61522574:61522824:61522636,0.715336,3.976780e-01,5.187970e-01,1,53,6,5,-0.017614,-0.017614,rs9912783,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_naive['rsID']

alt:cg03073402:SNPCENTER:chr19:42927676:C:G:42927563:42927789:42927676        cg03073402
alt:cg03169557:SNPCENTER:chr16:89598950:C:G:89598837:89599063:89598950        cg03169557
alt:cg05030077:SNPCENTER:chr16:2255199:C:G:2255086:2255312:2255199            cg05030077
alt:cg05066959:SNPCENTER:chr8:41519308:C:G:41519195:41519421:41519308         cg05066959
alt:cg05228284:SNPCENTER:chr19:2720847:C:G:2720734:2720960:2720847            cg05228284
                                                                                ...
alt:rs9478143:PEAKCENTER:chr6:150862035:A:G:150861632:150862271:150862051      rs9478143
alt:rs953471:PEAKCENTER:chr9:124221903:G:A:124221758:124221963:124221854        rs953471
alt:rs965034941:SNPCENTER:chr19:1999195:CCA:C:1999082:1999308:1999195        rs965034941
alt:rs983392:PEAKCENTER:chr11:59923508:A:G:59923333:59923833:59923583           rs983392
alt:rs9912783:PEAKCENTER:chr17:61522705:C:T:61522574:61522824:61522636         rs9912783
Name: rsID, Length: 855, dtype: object

In [5]:
df_imgl = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/iMGL_MPRA/iMGL MPRA Library.csv',index_col=0)
df_imgl

,library,chr,start,end,variant_id,effect_allele,non_effect_allele,source,statistic,pval,...,significance,Bellenguez_finemapping,caQTL_finemapping,lead_eQTL,LD_eQTL_ABC,LD_eQTL_sig_peak,Schwartzentruber_finemapping,Bellenguez_gwas,Jansen_gwas,Kunkle_gwas
1,MAIN_LIB_00001,chr1,99728749.0,99728750.0,rs7522921,C,G,Significant_Peak,7.429402e+00,0.006417,...,True,0,0,0,0,1,0,0,0,0
2,MAIN_LIB_00003,chr1,99737167.0,99737168.0,rs4333869,A,G,Significant_Peak,1.632639e+01,0.000053,...,True,0,0,0,0,1,0,0,0,0
3,MAIN_LIB_00005,chr1,99737287.0,99737288.0,rs11166315,C,G,Significant_Peak,4.267174e+00,0.038855,...,False,0,0,0,0,1,0,0,0,0
4,MAIN_LIB_00007,chr1,109740350.0,109740351.0,rs1332018,T,G,Significant_Peak,3.717170e-01,0.542070,...,False,0,0,0,0,1,0,0,0,0
5,MAIN_LIB_00009,chr1,111133952.0,111133953.0,rs12137472,T,G,Significant_Peak,2.500744e+00,0.113793,...,False,0,0,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11800,SCRMBL_SEQ_00246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.935405e-08,1.000000,...,False,0,0,0,0,0,0,0,0,0
11801,SCRMBL_SEQ_00247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.582521e-10,1.000000,...,False,0,0,0,0,0,0,0,0,0
11802,SCRMBL_SEQ_00248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.079577e-05,1.000000,...,False,0,0,0,0,0,0,0,0,0
11803,SCRMBL_SEQ_00249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.038579e-09,1.000000,...,False,0,0,0,0,0,0,0,0,0
11804,SCRMBL_SEQ_00250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.188261e-07,1.000000,...,False,0,0,0,0,0,0,0,0,0

In [6]:
rsid_overlap = df_naive[df_naive['rsID'].isin(df_imgl['variant_id'])]['rsID'].unique().tolist()

In [16]:
rsid_overlap

['rs10792832',
 'rs10863420',
 'rs10897011',
 'rs10905989',
 'rs11585858',
 'rs12459419',
 'rs12539172',
 'rs12703526',
 'rs143867193',
 'rs17462136',
 'rs2279590',
 'rs2526380',
 'rs2931819',
 'rs34039593',
 'rs34331363',
 'rs36026988',
 'rs3865444',
 'rs41289512',
 'rs4147929',
 'rs4575098',
 'rs4727455',
 'rs474479',
 'rs5157',
 'rs541458',
 'rs6014724',
 'rs6064392',
 'rs636317',
 'rs636341',
 'rs650366',
 'rs6733839',
 'rs7110631',
 'rs7158555',
 'rs718376',
 'rs7247551',
 'rs7283058',
 'rs76726049',
 'rs7920721',
 'rs7926344',
 'rs7926354',
 'rs7926729',
 'rs7930318',
 'rs7933202',
 'rs927174',
 'rs983392',
 'rs9912783']

In [7]:
df_imgl_overlap = df_imgl[df_imgl['variant_id'].isin(rsid_overlap)]

In [8]:
df_imgl_overlap_sig = df_imgl_overlap[df_imgl_overlap['significance']==True]

In [9]:
df_imgl_overlap_sig

,library,chr,start,end,variant_id,effect_allele,non_effect_allele,source,statistic,pval,...,significance,Bellenguez_finemapping,caQTL_finemapping,lead_eQTL,LD_eQTL_ABC,LD_eQTL_sig_peak,Schwartzentruber_finemapping,Bellenguez_gwas,Jansen_gwas,Kunkle_gwas
1226,MAIN_LIB_02451,chr19,44951509.0,44951510.0,rs7247551,A,G,ABC_Enhancer,13.411309,2.501118e-04,...,True,0,0,0,1,0,0,0,0,0
5187,MAIN_LIB_10373,chr11,60169453.0,60169454.0,rs7933202,A,C,Schwartzentruber_Finemapping,7.103208,7.694610e-03,...,True,0,0,0,0,0,1,0,0,1
5204,MAIN_LIB_10407,chr11,86077309.0,86077310.0,rs541458,T,C,Schwartzentruber_Finemapping,7.447390,6.352849e-03,...,True,0,0,0,0,0,1,0,0,0
5374,MAIN_LIB_10747,chr19,51225221.0,51225222.0,rs12459419,T,C,Schwartzentruber_Finemapping,38.927603,4.398173e-10,...,True,0,0,0,0,0,1,0,0,0
5382,MAIN_LIB_10763,chr20,56423488.0,56423489.0,rs6014724,A,G,Schwartzentruber_Finemapping,9.347651,2.232715e-03,...,True,1,0,0,0,0,1,1,1,0
11544,MAIN_LIB_23087,chr19,44848259.0,44848260.0,rs41289512,G,C,Jansen,39.810326,2.798616e-10,...,True,0,0,0,0,0,0,0,1,0

In [10]:
df_naive[df_naive['rsID'].isin(df_imgl_overlap_sig['variant_id'])]

,statistic,pval,fdr,df.test,df.dna,df.rna.full,df.rna.red,logFC,logFC_converted,RSID,...,ML_majorminor_diff_genomic_Mouse_Cortex_AgeC-model,ML_majorminor_diff_genomic_Mouse_Striatum_AgeB,ML_majorminor_diff_genomic_Mouse_Striatum_AgeC,ML_majorminor_diff_genomic_THP1_IFNB-Calvin,ML_majorminor_diff_genomic_THP1_IFNG-Calvin,ML_majorminor_diff_genomic_THP1_LPSIFNG-Calvin,ML_majorminor_diff_genomic_THP1_Naive-Calvin,ML_majorminor_diff_genomic_THP1_monocyte0729,ML_majorminor_diff_genomic_WTC11_IFNB,ML_majorminor_diff_genomic_WTC11_resting
alt:rs12459419:PEAKCENTER:chr19:51728477:C:T:51727829:51728966:51728557,2.285550,0.130584,0.219782,1,53,6,5,-0.030276,-0.030276,rs12459419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs41289512:PEAKCENTER:chr19:45351516:C:G:45351472:45351691:45351550,3.089071,0.078820,0.149426,1,53,6,5,0.031649,0.031649,rs41289512,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs541458:PEAKCENTER:chr11:85788351:C:T:85788212:85788484:85788350,0.731725,0.392325,0.513687,1,53,6,5,0.021282,-0.021282,rs541458,...,NaN,0.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs6014724:PEAKCENTER:chr20:54998544:A:G:54998217:54998717:54998467,0.060547,0.805633,0.871920,1,53,6,5,0.006914,0.006914,rs6014724,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs7247551:PEAKCENTER:chr19:44951509:G:A:44951240:44951740:44951490,0.490010,0.483923,0.603140,1,53,6,5,0.014384,-0.014384,rs7247551,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs7933202:PEAKCENTER:chr11:59936926:A:C:59936720:59937220:59936970,0.437384,0.508388,0.626328,1,53,6,5,0.015458,0.015458,rs7933202,...,NaN,-1.03,-0.8,NaN,NaN,NaN,NaN,NaN,-0.97,NaN

In [25]:
df_naive_sig = df_naive[df_naive['fdr']<=0.05]

df_naive_sig[df_naive_sig['rsID'].isin(df_imgl['variant_id'])]

,statistic,pval,fdr,df.test,df.dna,df.rna.full,df.rna.red,logFC,logFC_converted,RSID,...,ML_majorminor_diff_genomic_Mouse_Cortex_AgeC-model,ML_majorminor_diff_genomic_Mouse_Striatum_AgeB,ML_majorminor_diff_genomic_Mouse_Striatum_AgeC,ML_majorminor_diff_genomic_THP1_IFNB-Calvin,ML_majorminor_diff_genomic_THP1_IFNG-Calvin,ML_majorminor_diff_genomic_THP1_LPSIFNG-Calvin,ML_majorminor_diff_genomic_THP1_Naive-Calvin,ML_majorminor_diff_genomic_THP1_monocyte0729,ML_majorminor_diff_genomic_WTC11_IFNB,ML_majorminor_diff_genomic_WTC11_resting
alt:rs12539172:PEAKCENTER:chr7:100091795:T:C:100091083:100091870:100091810,98.802215,2.790222e-23,1.403317e-21,1,53,6,5,0.301112,-0.301112,rs12539172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs12703526:PEAKCENTER:chr7:143107588:G:T:143107527:143108024:143107693,31.752423,1.751306e-08,1.761608e-07,1,53,6,5,0.110598,0.110598,rs12703526,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs12703526:SNPCENTER:chr7:143107588:G:T:143107527:143108024:143107693,9.453366,2.107620e-03,7.179342e-03,1,53,6,5,0.091446,0.091446,rs12703526,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs143867193:PEAKCENTER:chr17:63426249:C:T:63425935:63426435:63426185,6.448173,1.110665e-02,2.986222e-02,1,53,6,5,0.043806,0.043806,rs143867193,...,NaN,0.59,1.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs2279590:PEAKCENTER:chr8:27456253:T:C:27456027:27456396:27456235,33.939849,5.684247e-09,6.000038e-08,1,53,6,5,0.121610,-0.121610,rs2279590,...,-0.72,NaN,NaN,0.63,NaN,NaN,0.61,NaN,NaN,NaN
alt:rs2526380:PEAKCENTER:chr17:56398006:C:G:56397833:56398333:56398083,8.963500,2.754268e-03,9.127515e-03,1,53,6,5,0.102553,0.102553,rs2526380,...,NaN,0.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs34331363:PEAKCENTER:chr6:32568439:C:T:32568156:32568656:32568406,7.074861,7.817290e-03,2.235379e-02,1,53,6,5,-0.076527,-0.076527,rs34331363,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs3865444:PEAKCENTER:chr19:51727962:C:A:51727829:51728966:51727912,25.610891,4.176752e-07,3.217228e-06,1,53,6,5,-0.101080,-0.101080,rs3865444,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs4147929:PEAKCENTER:chr19:1063443:A:G:1063220:1063720:1063470,7.013734,8.088679e-03,2.297615e-02,1,53,6,5,-0.066731,0.066731,rs4147929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs4575098:PEAKCENTER:chr1:161155392:G:A:161155022:161156276:161155354,9.822644,1.723764e-03,6.016350e-03,1,53,6,5,0.069052,0.069052,rs4575098,...,1.87,NaN,NaN,0.81,1.63,NaN,NaN,NaN,NaN,0.83
alt:rs4727455:PEAKCENTER:chr7:100473057:G:A:100472792:100473292:100473042,6.857312,8.827924e-03,2.474713e-02,1,53,6,5,-0.052105,-0.052105,rs4727455,...,-0.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
alt:rs474479:PEAKCENTER:chr11:85828551:C:G:85828483:85828719:85828611,17.651941,2.652445e-05,1.463123e-04,1,53,6,5,-0.120953,0.120953,rs474479,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.67,NaN,NaN
alt:rs636317:PEAKCENTER:chr11:60019150:C:T:60018954:60020211:60019210,10.461329,1.218995e-03,4.435068e-03,1,53,6,5,0.071621,-0.071621,rs636317,...,-7.29,-7.44,-6.88,-5.09,-6.56,-3.85,-7.42,-5.41,-7.80,-7.64
alt:rs636341:PEAKCENTER:chr11:60019161:A:C:60018954:60020211:60019088,35.133587,3.078452e-09,3.418281e-08,1,53,6,5,0.127043,-0.127043,rs636341,...,0.61,0.74,0.51,0.50,0.62,NaN,1.02,0.79,0.89,1.26
alt:rs6733839:PEAKCENTER:chr2:127892810:C:T:127891990:127893319:127892710,27.640002,1.461254e-07,1.249372e-06,1,53,6,5,0.185978,0.185978,rs6733839,...,-1.28,-0.78,-0.83,NaN,-0.61,NaN,-0.56,NaN,NaN,NaN
alt:rs6733839:PEAKCENTER:chr2:127892810:C:T:127892531:127893210:127892915,17.093125,3.559091e-05,1.901889e-04,1,53,6,5,0.111920,0.111920,rs6733839,...,-1.28,-0.78,-0.83,NaN,-0.61,NaN,NaN,NaN,NaN,NaN
alt:rs7926344:PEAKCENTER:chr11:59962166:G:A:59961830:59962330:59962080,51.779732,6.208945e-13,1.083398e-11,1,53,6,5,0.134362,0.134362,rs7926344,...,NaN,-1.55,-1.83,-1.14,-1.38,-1.23,-1.03,-2.47,-1.36,-1.59
alt:rs7926354:PEAKCENTER:chr11:59962189:G:A:59961830:59962330:59962080,21.047544,4.480268e-06,2.775818e-05,1,53,6,5,0.076905,0.076905,rs7926354,...,NaN,NaN,NaN,NaN,1.40,NaN,0.95,NaN,0.67,1.21
alt:rs7926354:SNPCENTER:chr11:59962189:G:A:59961830:59962330:59962080,8.781669,3.042727e-03,9.817101e-03,1,53,6,5,0.046788,0.046788,rs7926354,...,NaN,NaN,NaN,0.67,1.40,NaN,0.95,NaN,NaN,1.21
alt:rs7930318:PEAKCENTER:chr11:60033371:C:T:60033038:60033538:60033288,10.185314,1.415636e-03,5.022278e-03,1,53,6,5,0.124758,-0.124758,rs7930318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_imgl_overlap

,library,chr,start,end,variant_id,effect_allele,non_effect_allele,source,statistic,pval,...,significance,Bellenguez_finemapping,caQTL_finemapping,lead_eQTL,LD_eQTL_ABC,LD_eQTL_sig_peak,Schwartzentruber_finemapping,Bellenguez_gwas,Jansen_gwas,Kunkle_gwas
89,MAIN_LIB_00177,chr10,11678309.0,11678310.0,rs7920721,A,G,Significant_Peak,4.244355,3.938104e-02,...,False,1,0,0,0,1,1,0,0,1
187,MAIN_LIB_00373,chr11,86156833.0,86156834.0,rs10792832,A,G,Significant_Peak,NaN,NaN,...,False,1,1,0,1,1,1,0,0,0
1225,MAIN_LIB_02449,chr19,44943904.0,44943905.0,rs5157,T,C,ABC_Enhancer,1.806012,1.789874e-01,...,False,0,0,0,1,0,0,0,0,0
1226,MAIN_LIB_02451,chr19,44951509.0,44951510.0,rs7247551,A,G,ABC_Enhancer,13.411309,2.501118e-04,...,True,0,0,0,1,0,0,0,0,0
1245,MAIN_LIB_02489,chr2,127135234.0,127135235.0,rs6733839,T,C,ABC_Enhancer,1.147829,2.840041e-01,...,False,1,0,1,1,0,1,1,0,1
1271,MAIN_LIB_02541,chr21,24420764.0,24420765.0,rs7283058,A,G,ABC_Enhancer,3.942853,4.707089e-02,...,False,0,0,0,1,0,0,0,0,0
1604,MAIN_LIB_03207,chr10,11677594.0,11677595.0,rs10905989,T,C,caQTL_finemapping,0.000386,9.843230e-01,...,False,0,1,0,1,1,0,0,0,0
4814,MAIN_LIB_09627,chr1,161185602.0,161185603.0,rs4575098,A,G,Schwartzentruber_Finemapping,0.366709,5.448036e-01,...,False,0,0,0,0,0,1,0,1,0
4815,MAIN_LIB_09629,chr1,161186243.0,161186244.0,rs11585858,A,C,Schwartzentruber_Finemapping,2.911236,8.796445e-02,...,False,0,0,0,0,0,1,0,0,0
4848,MAIN_LIB_09695,chr1,207626529.0,207626530.0,rs10863420,A,C,Schwartzentruber_Finemapping,1.318965,2.507778e-01,...,False,0,0,0,0,0,1,0,0,0
5013,MAIN_LIB_10025,chr6,32600662.0,32600663.0,rs34331363,T,C,Schwartzentruber_Finemapping,0.017839,8.937495e-01,...,False,0,0,0,0,0,1,0,0,0
5060,MAIN_LIB_10119,chr7,143410495.0,143410496.0,rs12703526,T,G,Schwartzentruber_Finemapping,0.549892,4.583620e-01,...,False,0,0,0,0,0,1,0,0,0
5097,MAIN_LIB_10193,chr7,100473057.0,100473058.0,rs4727455,A,G,Schwartzentruber_Finemapping,0.147966,7.004867e-01,...,False,0,0,0,0,0,1,0,0,0
5100,MAIN_LIB_10199,chr8,27598736.0,27598737.0,rs2279590,T,C,Schwartzentruber_Finemapping,0.020460,8.862585e-01,...,False,0,0,0,0,0,1,0,0,0
5184,MAIN_LIB_10367,chr11,60194716.0,60194717.0,rs7926354,A,G,Schwartzentruber_Finemapping,0.702939,4.017981e-01,...,False,0,0,0,0,0,1,0,0,0
5185,MAIN_LIB_10369,chr11,60193954.0,60193955.0,rs10897011,A,G,Schwartzentruber_Finemapping,0.000106,9.918009e-01,...,False,0,0,0,0,0,1,0,0,0
5186,MAIN_LIB_10371,chr11,60194313.0,60194314.0,rs7926729,T,C,Schwartzentruber_Finemapping,5.417138,1.994002e-02,...,False,0,0,0,0,0,1,0,0,0
5187,MAIN_LIB_10373,chr11,60169453.0,60169454.0,rs7933202,A,C,Schwartzentruber_Finemapping,7.103208,7.694610e-03,...,True,0,0,0,0,0,1,0,0,1
5188,MAIN_LIB_10375,chr11,60194693.0,60194694.0,rs7926344,A,G,Schwartzentruber_Finemapping,6.464527,1.100489e-02,...,False,0,0,0,0,0,1,0,0,0
5194,MAIN_LIB_10387,chr11,60265898.0,60265899.0,rs7930318,T,C,Schwartzentruber_Finemapping,5.690755,1.705451e-02,...,False,0,0,0,0,0,1,0,0,0
5195,MAIN_LIB_10389,chr11,60235462.0,60235463.0,rs718376,A,G,Schwartzentruber_Finemapping,0.727942,3.935511e-01,...,False,0,0,0,0,0,1,0,0,0
5196,MAIN_LIB_10391,chr11,60251677.0,60251678.0,rs636317,T,C,Schwartzentruber_Finemapping,0.236397,6.268206e-01,...,False,0,0,0,0,0,1,0,0,0
5197,MAIN_LIB_10393,chr11,60251688.0,60251689.0,rs636341,A,C,Schwartzentruber_Finemapping,5.678732,1.717177e-02,...,False,0,0,0,0,0,1,0,0,0
5198,MAIN_LIB_10395,chr11,60156035.0,60156036.0,rs983392,A,G,Schwartzentruber_Finemapping,3.295415,6.947354e-02,...,False,0,0,0,0,0,1,0,0,0
5204,MAIN_LIB_10407,chr11,86077309.0,86077310.0,rs541458,T,C,Schwartzentruber_Finemapping,7.447390,6.352849e-03,...,True,0,0,0,0,0,1,0,0,0
5205,MAIN_LIB_10409,chr11,86117509.0,86117510.0,rs474479,C,G,Schwartzentruber_Finemapping,NaN,NaN,...,False,0,0,0,0,0,1,0,0,0
5210,MAIN_LIB_10419,chr11,86145145.0,86145146.0,rs7110631,C,G,Schwartzentruber_Finemapping,0.419577,5.171481e-01,...,False,0,0,0,0,0,1,0,0,0
5226,MAIN_LIB_10451,chr14,52895288.0,52895289.0,rs7158555,A,G,Schwartzentruber_Finemapping,5.759316,1.640145e-02,...,False,0,0,0,0,0,1,0,0,0
5229,MAIN_LIB_10457,chr14,92472038.0,92472039.0,rs36026988,T,C,Schwartzentruber_Finemapping,0.544176,4.607071e-01,...,False,0,0,0,0,0,1,0,0,0
5287,MAIN_LIB_10573,chr15,58768943.0,58768944.0,rs650366,A,G,Schwartzentruber_Finemapping,6.699906,9.641801e-03,...,False,0,0,0,0,0,1,0,0,0
5337,MAIN_LIB_10673,chr17,58320645.0,58320646.0,rs2526380,C,G,Schwartzentruber_Finemapping,1.048508,3.058509e-01,...,False,0,0,0,0,0,1,0,0,0
5353,MAIN_LIB_10705,chr17,63426249.0,63426250.0,rs143867193,T,C,Schwartzentruber_Finemapping,0.364290,5.461333e-01,...,False,0,0,0,0,0,1,0,0,0
5360,MAIN_LIB_10719,chr17,63445344.0,63445345.0,rs9912783,T,C,Schwartzentruber_Finemapping,0.283399,5.944821e-01,...,False,0,0,0,0,0,1,0,0,0
5373,MAIN_LIB_10745,chr19,51224706.0,51224707.0,rs3865444,A,C,Schwartzentruber_Finemapping,2.542552,1.108155e-01,...,False,0,0,0,0,0,1,0,1,0
5374,MAIN_LIB_10747,chr19,51225221.0,51225222.0,rs12459419,T,C,Schwartzentruber_Finemapping,38.927603,4.398173e-10,...,True,0,0,0,0,0,1,0,0,0
5382,MAIN_LIB_10763,chr20,56423488.0,56423489.0,rs6014724,A,G,Schwartzentruber_Finemapping,9.347651,2.232715e-03,...,True,1,0,0,0,0,1,1,1,0
5386,MAIN_LIB_10771,chr20,56412160.0,56412161.0,rs17462136,C,G,Schwartzentruber_Finemapping,1.601227,2.057294e-01,...,False,1,0,0,0,0,1,0,0,0
5387,MAIN_LIB_10773,chr20,56409712.0,56409713.0,rs6064392,T,G,Schwartzentruber_Finemapping,1.598383,2.061325e-01,...,False,1,0,0,0,0,1,0,0,0
5395,MAIN_LIB_10789,chr20,56440110.0,56440111.0,rs927174,A,C,Schwartzentruber_Finemapping,0.656777,4.177003e-01,...,False,0,0,0,0,0,1,0,0,0
5670,MAIN_LIB_11339,chr6,32602534.0,32602535.0,rs34039593,T,G,PD_Finemapping,6.516509,1.068776e-02,...,False,0,0,0,0,0,0,0,0,0
7458,MAIN_LIB_14915,chr17,3386296.0,3386297.0,rs2931819,G,C,miga_lead_sig_snps,4.313938,3.780137e-02,...,False,0,0,1,0,0,0,0,0,0
11532,MAIN_LIB_23063,chr7,100494172.0,100494173.0,rs12539172,C,T,Kunkle,0.989111,3.199597e-01,...,False,0,0,0,0,0,0,0,0,1
11542,MAIN_LIB_23083,chr18,58522227.0,58522228.0,rs76726049,C,T,Jansen,0.770173,3.801635e-01,...,False,0,0,0,0,0,0,0,1,0
11543,MAIN_LIB_23085,chr19,1063444.0,1063445.0,rs4147929,G,C,Jansen,0.995297,3.184512e-01,...,False,0,0,0,0,0,0,0,1,0
11544,MAIN_LIB_23087,chr19,44848259.0,44848260.0,rs41289512,G,C,Jansen,39.810326,2.798616e-10,...,True,0,0,0,0,0,0,0,1,0