In [77]:
import pandas as pd
def expand_annotation_32barcodes_from_enhancer_annotation(enhancer_annotation_path, save_path):
    df = pd.read_csv(enhancer_annotation_path,index_col=0)

    # Assuming 'df' is your original DataFrame
    # Duplicate the DataFrame
    duplicated_df = pd.concat([df, df]).sort_index(kind='merge')

    # Create an alternating index
    new_index = [f"{index}_ALT" if i % 2 == 0 else f"{index}_REF" for i, index in enumerate(duplicated_df.index)]

    # Assign the new index to the DataFrame
    duplicated_df.index = new_index

    # Now duplicated_df has each row duplicated with alternating "_ALT" and "_REF" suffixes in the index
    df = duplicated_df

    # Expand dataframe to have 32 rows for each original row
    expanded_df = pd.DataFrame()

    for _, row in df.iterrows():
        for i in range(1, 33):
            new_row = row.copy()
            new_row['Barcode_number'] = i
            expanded_df = pd.concat([expanded_df, new_row], axis=1)
    expanded_df = expanded_df.T
    expanded_df["sample_barcodes"] = (expanded_df.index + "_Barcode_" + expanded_df["Barcode_number"].astype(str)).tolist()

    expanded_df["Barcode_Allele"] = expanded_df["Barcode_number"].astype(str) + expanded_df.index.str.slice(-4,)
    expanded_df["Allele_String"] = expanded_df.index.str.slice(-3,)
    expanded_df["Test_Allele"] = expanded_df["Test"]+"_"+expanded_df["Allele_String"]
    expanded_df["Animal_Allele"] = expanded_df["Animal"]+"_"+expanded_df["Allele_String"]
    expanded_df["Tissue_Allele"] = expanded_df["Tissue"]+"_"+expanded_df["Allele_String"]
    #expanded_df = expanded_df.reset_index()
    expanded_df = expanded_df.set_index("sample_barcodes")
    expanded_df.rename(columns={"index": "sample_allele"}, inplace=True)
    expanded_df.index.name = None
    if save_path:
        expanded_df.to_csv(save_path)
    return expanded_df

import pandas as pd
def expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path, save_path):
    df = pd.read_csv(enhancer_annotation_path,index_col=0)

    # Assuming 'df' is your original DataFrame
    # Duplicate the DataFrame
    duplicated_df = pd.concat([df, df]).sort_index(kind='merge')

    # Create an alternating index
    new_index = [f"{index}_ALT" if i % 2 == 0 else f"{index}_REF" for i, index in enumerate(duplicated_df.index)]

    # Assign the new index to the DataFrame
    duplicated_df.index = new_index

    # Now duplicated_df has each row duplicated with alternating "_ALT" and "_REF" suffixes in the index
    df = duplicated_df

    # Expand dataframe to have 32 rows for each original row
    expanded_df = pd.DataFrame()

    for _, row in df.iterrows():
        for i in range(1, 6):
            new_row = row.copy()
            new_row['Barcode_number'] = i
            expanded_df = pd.concat([expanded_df, new_row], axis=1)
    expanded_df = expanded_df.T
    expanded_df["sample_barcodes"] = (expanded_df.index + "_Barcode_" + expanded_df["Barcode_number"].astype(str)).tolist()

    expanded_df["Barcode_Allele"] = expanded_df["Barcode_number"].astype(str) + expanded_df.index.str.slice(-4,)
    expanded_df["Allele_String"] = expanded_df.index.str.slice(-3,)
    expanded_df["Test_Allele"] = expanded_df["Test"]+"_"+expanded_df["Allele_String"]
    expanded_df["Animal_Allele"] = expanded_df["Animal"]+"_"+expanded_df["Allele_String"]
    expanded_df["Tissue_Allele"] = expanded_df["Tissue"]+"_"+expanded_df["Allele_String"]
    #expanded_df = expanded_df.reset_index()
    expanded_df = expanded_df.set_index("sample_barcodes")
    expanded_df.rename(columns={"index": "sample_allele"}, inplace=True)
    expanded_df.index.name = None
    if save_path:
        expanded_df.to_csv(save_path)
    return expanded_df

import pandas as pd
def expand_annotation_3barcodes_from_enhancer_annotation(enhancer_annotation_path, save_path):
    df = pd.read_csv(enhancer_annotation_path,index_col=0)

    # Assuming 'df' is your original DataFrame
    # Duplicate the DataFrame
    duplicated_df = pd.concat([df, df]).sort_index(kind='merge')

    # Create an alternating index
    new_index = [f"{index}_ALT" if i % 2 == 0 else f"{index}_REF" for i, index in enumerate(duplicated_df.index)]

    # Assign the new index to the DataFrame
    duplicated_df.index = new_index

    # Now duplicated_df has each row duplicated with alternating "_ALT" and "_REF" suffixes in the index
    df = duplicated_df

    # Expand dataframe to have 32 rows for each original row
    expanded_df = pd.DataFrame()

    for _, row in df.iterrows():
        for i in range(1, 4):
            new_row = row.copy()
            new_row['Barcode_number'] = i
            expanded_df = pd.concat([expanded_df, new_row], axis=1)
    expanded_df = expanded_df.T
    expanded_df["sample_barcodes"] = (expanded_df.index + "_Barcode_" + expanded_df["Barcode_number"].astype(str)).tolist()

    expanded_df["Barcode_Allele"] = expanded_df["Barcode_number"].astype(str) + expanded_df.index.str.slice(-4,)
    expanded_df["Allele_String"] = expanded_df.index.str.slice(-3,)
    expanded_df["Test_Allele"] = expanded_df["Test"]+"_"+expanded_df["Allele_String"]
    expanded_df["Animal_Allele"] = expanded_df["Animal"]+"_"+expanded_df["Allele_String"]
    expanded_df["Tissue_Allele"] = expanded_df["Tissue"]+"_"+expanded_df["Allele_String"]
    #expanded_df = expanded_df.reset_index()
    expanded_df = expanded_df.set_index("sample_barcodes")
    expanded_df.rename(columns={"index": "sample_allele"}, inplace=True)
    expanded_df.index.name = None
    if save_path:
        expanded_df.to_csv(save_path)
    return expanded_df

In [12]:
#Expand 32 anootation HEK293T
expand_annotation_32barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_HEK293T.csv', 
    save_path='annotation_barcodes/mpra3_annot_HEK293T_barcodes.csv')

,Tissue,Delivery,Date,Animal,Test,Function,Parent,Purification,Barcode_number,Barcode_Allele,Allele_String,Test_Allele,Animal_Allele,Tissue_Allele
Naive_HEK293T_ZC65_R_ALT_Barcode_1,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC65_R,Control_cell,HEK293T,Column,1,1_ALT,ALT,Naive_HEK293T_ZC65_R_ALT,HEK293T_ALT,HEK293T_ALT
Naive_HEK293T_ZC65_R_ALT_Barcode_2,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC65_R,Control_cell,HEK293T,Column,2,2_ALT,ALT,Naive_HEK293T_ZC65_R_ALT,HEK293T_ALT,HEK293T_ALT
Naive_HEK293T_ZC65_R_ALT_Barcode_3,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC65_R,Control_cell,HEK293T,Column,3,3_ALT,ALT,Naive_HEK293T_ZC65_R_ALT,HEK293T_ALT,HEK293T_ALT
Naive_HEK293T_ZC65_R_ALT_Barcode_4,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC65_R,Control_cell,HEK293T,Column,4,4_ALT,ALT,Naive_HEK293T_ZC65_R_ALT,HEK293T_ALT,HEK293T_ALT
Naive_HEK293T_ZC65_R_ALT_Barcode_5,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC65_R,Control_cell,HEK293T,Column,5,5_ALT,ALT,Naive_HEK293T_ZC65_R_ALT,HEK293T_ALT,HEK293T_ALT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Naive_HEK293T_ZC81_R_REF_Barcode_28,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC81_R,Control_cell,HEK293T,Column,28,28_REF,REF,Naive_HEK293T_ZC81_R_REF,HEK293T_REF,HEK293T_REF
Naive_HEK293T_ZC81_R_REF_Barcode_29,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC81_R,Control_cell,HEK293T,Column,29,29_REF,REF,Naive_HEK293T_ZC81_R_REF,HEK293T_REF,HEK293T_REF
Naive_HEK293T_ZC81_R_REF_Barcode_30,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC81_R,Control_cell,HEK293T,Column,30,30_REF,REF,Naive_HEK293T_ZC81_R_REF,HEK293T_REF,HEK293T_REF
Naive_HEK293T_ZC81_R_REF_Barcode_31,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC81_R,Control_cell,HEK293T,Column,31,31_REF,REF,Naive_HEK293T_ZC81_R_REF,HEK293T_REF,HEK293T_REF
Naive_HEK293T_ZC81_R_REF_Barcode_32,HEK293T,Fugene6,NaN,HEK293T,Naive_HEK293T_ZC81_R,Control_cell,HEK293T,Column,32,32_REF,REF,Naive_HEK293T_ZC81_R_REF,HEK293T_REF,HEK293T_REF

In [ ]:
#Expand 32 annotation
expand_annotation_32barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_THP1.csv', 
    save_path='annotation_barcodes/mpra3_annot_THP1_barcodes.csv')

#THP1 Interaction
import pandas as pd
THP1_annotation = pd.read_csv('annotation_barcodes/mpra3_annot_THP1_barcodes.csv',index_col=0)

THP1_annotation['Allele'] = THP1_annotation['Allele_String'].map({'ALT': 1, 'REF': 0})
THP1_annotation["IFNB_interaction"] = THP1_annotation["IFNB"] * THP1_annotation["Allele"]
THP1_annotation["IFNG_interaction"] = THP1_annotation["IFNG"] * THP1_annotation["Allele"]
THP1_annotation["LPSIFNG_interaction"] = THP1_annotation["LPSIFNG"] * THP1_annotation["Allele"]
THP1_annotation["Naive_interaction"] = THP1_annotation["Naive_Macrophage"] * THP1_annotation["Allele"]
THP1_annotation.to_csv('annotation_barcodes/mpra3_annot_THP1_barcodes_interaction.csv')

#Split annotation
THP1 = pd.read_csv('annotation_barcodes/mpra3_annot_THP1_barcodes_interaction.csv',index_col=0)
THP1[THP1["IFNB"]==1].to_csv("annotation_barcodes/mpra3_annot_THP1_IFNB_barcodes.csv")
THP1[THP1["IFNG"]==1].to_csv("annotation_barcodes/mpra3_annot_THP1_IFNG_barcodes.csv")
THP1[THP1["LPSIFNG"]==1].to_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNG_barcodes.csv")
THP1[THP1["Naive_Macrophage"]==1].to_csv("annotation_barcodes/mpra3_annot_THP1_Naive_barcodes.csv")
THP1[THP1["Tissue"]=="THP1_Monocyte"].to_csv("annotation_barcodes/mpra3_annot_THP1_Monocyte_barcodes.csv")

THP1 = pd.read_csv('annotation_barcodes/mpra3_annot_THP1_barcodes_interaction.csv',index_col=0)
THP1[(THP1["IFNB"]==1) | (THP1["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_THP1_IFNBvsNaive_barcodes.csv")
THP1[(THP1["IFNG"]==1) | (THP1["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_THP1_IFNGvsNaive_barcodes.csv")
THP1[(THP1["LPSIFNG"]==1) | (THP1["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNGvsNaive_barcodes.csv")
THP1[(THP1["LPSIFNG"]==1) | (THP1["IFNG"]==1)].to_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNGvsIFNG_barcodes.csv")
THP1[(THP1["Tissue"]=="THP1_Monocyte") | (THP1["Tissue"]=="THP1_Naive")].to_csv("annotation_barcodes/mpra3_annot_THP1_MacrophagevsMonocyte_barcodes.csv")

#Split barcodes according to annotation
import pandas as pd
THP1_barcodes = pd.read_csv("read_counts_R1R2/THP1_DNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNB_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_IFNB_DNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_IFNG_DNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_LPSIFNG_DNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_Naive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_Naive_DNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_Monocyte_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_Monocyte_DNA_matched_barcodes_reshaped.csv")

THP1_barcodes = pd.read_csv("read_counts_R1R2/THP1_RNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNB_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_IFNB_RNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_IFNG_RNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_LPSIFNG_RNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_Naive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_Naive_RNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_Monocyte_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_Monocyte_RNA_matched_barcodes_reshaped.csv")

#Split barcodes according to annotation
import pandas as pd
THP1_barcodes = pd.read_csv("read_counts_R1R2/THP1_DNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNBvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_IFNBvsNaive_DNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_IFNGvsNaive_DNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_LPSIFNGvsNaive_DNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNGvsIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_LPSIFNGvsIFNG_DNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_MacrophagevsMonocyte_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_MacrophagevsMonocyte_DNA_matched_barcodes_reshaped.csv")

#Split barcodes according to annotation
import pandas as pd
THP1_barcodes = pd.read_csv("read_counts_R1R2/THP1_RNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNBvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_IFNBvsNaive_RNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_IFNGvsNaive_RNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_LPSIFNGvsNaive_RNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNGvsIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_LPSIFNGvsIFNG_RNA_matched_barcodes_reshaped.csv")
THP1_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1_MacrophagevsMonocyte_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1_MacrophagevsMonocyte_RNA_matched_barcodes_reshaped.csv")

In [ ]:
#Expand 32 annotation
expand_annotation_32barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_HMC3.csv', 
    save_path='annotation_barcodes/mpra3_annot_HMC3_barcodes.csv')

#Split annotation
HMC3 = pd.read_csv('annotation_barcodes/mpra3_annot_HMC3_barcodes.csv',index_col=0)
HMC3[HMC3["IFNB"]==1].to_csv("annotation_barcodes/mpra3_annot_HMC3_IFNB_barcodes.csv")
HMC3[HMC3["IFNG"]==1].to_csv("annotation_barcodes/mpra3_annot_HMC3_IFNG_barcodes.csv")
HMC3[HMC3["LPSIFNG"]==1].to_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNG_barcodes.csv")
HMC3[HMC3["Naive_Macrophage"]==1].to_csv("annotation_barcodes/mpra3_annot_HMC3_Naive_barcodes.csv")

#Split barcodes according to annotation
import pandas as pd
HMC3_barcodes = pd.read_csv("read_counts_R1R2/HMC3_DNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNB_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_IFNB_DNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_IFNG_DNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_LPSIFNG_DNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_Naive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_Naive_DNA_matched_barcodes_reshaped.csv")

HMC3_barcodes = pd.read_csv("read_counts_R1R2/HMC3_RNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNB_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_IFNB_RNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_IFNG_RNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_LPSIFNG_RNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_Naive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_Naive_RNA_matched_barcodes_reshaped.csv")

#HMC3 Interaction
import pandas as pd
HMC3_annotation = pd.read_csv('annotation_barcodes/mpra3_annot_HMC3_barcodes.csv',index_col=0)

HMC3_annotation['Allele'] = HMC3_annotation['Allele_String'].map({'ALT': 1, 'REF': 0})

HMC3_annotation["IFNB_interaction"] = HMC3_annotation["IFNB"] * HMC3_annotation["Allele"]
HMC3_annotation["IFNG_interaction"] = HMC3_annotation["IFNG"] * HMC3_annotation["Allele"]
HMC3_annotation["LPSIFNG_interaction"] = HMC3_annotation["LPSIFNG"] * HMC3_annotation["Allele"]
HMC3_annotation["Naive_interaction"] = HMC3_annotation["Naive_Macrophage"] * HMC3_annotation["Allele"]
HMC3_annotation.to_csv('annotation_barcodes/mpra3_annot_HMC3_barcodes_interaction.csv')

HMC3 = pd.read_csv('annotation_barcodes/mpra3_annot_HMC3_barcodes_interaction.csv',index_col=0)
HMC3[(HMC3["IFNB"]==1) | (HMC3["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_HMC3_IFNBvsNaive_barcodes.csv")
HMC3[(HMC3["IFNG"]==1) | (HMC3["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_HMC3_IFNGvsNaive_barcodes.csv")
HMC3[(HMC3["LPSIFNG"]==1) | (HMC3["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNGvsNaive_barcodes.csv")
HMC3[(HMC3["LPSIFNG"]==1) | (HMC3["IFNG"]==1)].to_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNGvsIFNG_barcodes.csv")

#Split barcodes according to annotation
import pandas as pd
HMC3_barcodes = pd.read_csv("read_counts_R1R2/HMC3_DNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNBvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_IFNBvsNaive_DNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_IFNGvsNaive_DNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_LPSIFNGvsNaive_DNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNGvsIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_LPSIFNGvsIFNG_DNA_matched_barcodes_reshaped.csv")


#Split barcodes according to annotation
import pandas as pd
HMC3_barcodes = pd.read_csv("read_counts_R1R2/HMC3_RNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNBvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_IFNBvsNaive_RNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_IFNGvsNaive_RNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_LPSIFNGvsNaive_RNA_matched_barcodes_reshaped.csv")
HMC3_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNGvsIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/HMC3_LPSIFNGvsIFNG_RNA_matched_barcodes_reshaped.csv")

In [116]:
#Expand 5 annotation, BrainR1R2merged20240404
expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_BrainR1R2merged.csv', 
    save_path='annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_barcodes.csv')

import pandas as pd
#Split annotation
BrainR1R2merged20240404 = pd.read_csv('annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_barcodes.csv',index_col=0)

BrainR1R2merged20240404[BrainR1R2merged20240404["Striatum"]==1].to_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Striatum_barcodes.csv")
BrainR1R2merged20240404[BrainR1R2merged20240404["Hippocampus"]==1].to_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Hippocampus_barcodes.csv")
BrainR1R2merged20240404[BrainR1R2merged20240404["Cortex"]==1].to_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Cortex_barcodes.csv")

#Split barcodes according to annotation
import pandas as pd
BrainR1R2merged20240404_barcodes = pd.read_csv("read_counts_R1R2/BrainR1R2merged20240404_DNA_matched_barcodes_reshaped.csv",index_col=0)
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Striatum_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_Striatum_DNA_matched_barcodes_reshaped.csv")
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Hippocampus_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_Hippocampus_DNA_matched_barcodes_reshaped.csv")
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Cortex_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_Cortex_DNA_matched_barcodes_reshaped.csv")

BrainR1R2merged20240404_barcodes = pd.read_csv("read_counts_R1R2/BrainR1R2merged20240404_RNA_matched_barcodes_reshaped.csv",index_col=0)
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Striatum_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_Striatum_RNA_matched_barcodes_reshaped.csv")
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Hippocampus_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_Hippocampus_RNA_matched_barcodes_reshaped.csv")
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_Cortex_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_Cortex_RNA_matched_barcodes_reshaped.csv")

#BrainR1R2merged20240404 Interaction
import pandas as pd
BrainR1R2merged20240404_annotation = pd.read_csv('annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_barcodes.csv',index_col=0)
BrainR1R2merged20240404_annotation['Allele'] = BrainR1R2merged20240404_annotation['Allele_String'].map({'ALT': 1, 'REF': 0})
BrainR1R2merged20240404_annotation["Striatum_interaction"] = BrainR1R2merged20240404_annotation["Striatum"] * BrainR1R2merged20240404_annotation["Allele"]
BrainR1R2merged20240404_annotation["Hippocampus_interaction"] = BrainR1R2merged20240404_annotation["Hippocampus"] * BrainR1R2merged20240404_annotation["Allele"]
BrainR1R2merged20240404_annotation["Cortex_interaction"] = BrainR1R2merged20240404_annotation["Cortex"] * BrainR1R2merged20240404_annotation["Allele"]
BrainR1R2merged20240404_annotation.to_csv('annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_barcodes_interaction.csv')

BrainR1R2merged20240404 = pd.read_csv('annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_barcodes_interaction.csv',index_col=0)
BrainR1R2merged20240404[(BrainR1R2merged20240404["Striatum"]==1) | (BrainR1R2merged20240404["Cortex"]==1)].to_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_StriatumvsCortex_barcodes.csv")
BrainR1R2merged20240404[(BrainR1R2merged20240404["Hippocampus"]==1) | (BrainR1R2merged20240404["Cortex"]==1)].to_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_HippocampusvsCortex_barcodes.csv")

#Split barcodes according to annotation
import pandas as pd
BrainR1R2merged20240404_barcodes = pd.read_csv("read_counts_R1R2/BrainR1R2merged20240404_DNA_matched_barcodes_reshaped.csv",index_col=0)
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_StriatumvsCortex_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_StriatumvsCortex_DNA_matched_barcodes_reshaped.csv")
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_HippocampusvsCortex_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_HippocampusvsCortex_DNA_matched_barcodes_reshaped.csv")

#Split barcodes according to annotation
import pandas as pd
BrainR1R2merged20240404_barcodes = pd.read_csv("read_counts_R1R2/BrainR1R2merged20240404_RNA_matched_barcodes_reshaped.csv",index_col=0)
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_StriatumvsCortex_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_StriatumvsCortex_RNA_matched_barcodes_reshaped.csv")
BrainR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_HippocampusvsCortex_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/BrainR1R2merged20240404_HippocampusvsCortex_RNA_matched_barcodes_reshaped.csv")

In [3]:
#Expand 5 annotation, BrainR1R2merged20240404
expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_THP1Monocyte.csv',save_path='annotation_barcodes/mpra3_annot_THP1Monocyte20240412_barcodes.csv')

,Tissue,Delivery,Date,Animal,Test,Function,Parent,IFNB,IFNG,LPSIFNG,Naive_Macrophage,THP1_Monocytes,Barcode_number,Barcode_Allele,Allele_String,Test_Allele,Animal_Allele,Tissue_Allele
Naive_THP1mono_ZC111_R_ALT_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_ALT,ALT,Naive_THP1mono_ZC111_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC111_R_ALT_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_ALT,ALT,Naive_THP1mono_ZC111_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC111_R_ALT_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_ALT,ALT,Naive_THP1mono_ZC111_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC111_R_ALT_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_ALT,ALT,Naive_THP1mono_ZC111_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC111_R_ALT_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_ALT,ALT,Naive_THP1mono_ZC111_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC111_R_REF_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_REF,REF,Naive_THP1mono_ZC111_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC111_R_REF_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_REF,REF,Naive_THP1mono_ZC111_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC111_R_REF_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_REF,REF,Naive_THP1mono_ZC111_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC111_R_REF_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_REF,REF,Naive_THP1mono_ZC111_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC111_R_REF_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_REF,REF,Naive_THP1mono_ZC111_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC112_R_ALT_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_ALT,ALT,Naive_THP1mono_ZC112_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC112_R_ALT_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_ALT,ALT,Naive_THP1mono_ZC112_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC112_R_ALT_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_ALT,ALT,Naive_THP1mono_ZC112_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC112_R_ALT_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_ALT,ALT,Naive_THP1mono_ZC112_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC112_R_ALT_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_ALT,ALT,Naive_THP1mono_ZC112_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC112_R_REF_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_REF,REF,Naive_THP1mono_ZC112_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC112_R_REF_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_REF,REF,Naive_THP1mono_ZC112_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC112_R_REF_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_REF,REF,Naive_THP1mono_ZC112_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC112_R_REF_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_REF,REF,Naive_THP1mono_ZC112_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC112_R_REF_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC112_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_REF,REF,Naive_THP1mono_ZC112_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC113_R_ALT_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_ALT,ALT,Naive_THP1mono_ZC113_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC113_R_ALT_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_ALT,ALT,Naive_THP1mono_ZC113_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC113_R_ALT_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_ALT,ALT,Naive_THP1mono_ZC113_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC113_R_ALT_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_ALT,ALT,Naive_THP1mono_ZC113_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC113_R_ALT_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_ALT,ALT,Naive_THP1mono_ZC113_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC113_R_REF_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_REF,REF,Naive_THP1mono_ZC113_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC113_R_REF_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_REF,REF,Naive_THP1mono_ZC113_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC113_R_REF_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_REF,REF,Naive_THP1mono_ZC113_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC113_R_REF_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_REF,REF,Naive_THP1mono_ZC113_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC113_R_REF_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC113_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_REF,REF,Naive_THP1mono_ZC113_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC37_R_ALT_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_ALT,ALT,Naive_THP1mono_ZC37_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC37_R_ALT_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_ALT,ALT,Naive_THP1mono_ZC37_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC37_R_ALT_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_ALT,ALT,Naive_THP1mono_ZC37_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC37_R_ALT_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_ALT,ALT,Naive_THP1mono_ZC37_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC37_R_ALT_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_ALT,ALT,Naive_THP1mono_ZC37_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC37_R_REF_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_REF,REF,Naive_THP1mono_ZC37_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC37_R_REF_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_REF,REF,Naive_THP1mono_ZC37_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC37_R_REF_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_REF,REF,Naive_THP1mono_ZC37_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC37_R_REF_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_REF,REF,Naive_THP1mono_ZC37_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC37_R_REF_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC37_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_REF,REF,Naive_THP1mono_ZC37_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC60_R_ALT_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_ALT,ALT,Naive_THP1mono_ZC60_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC60_R_ALT_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_ALT,ALT,Naive_THP1mono_ZC60_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC60_R_ALT_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_ALT,ALT,Naive_THP1mono_ZC60_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC60_R_ALT_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_ALT,ALT,Naive_THP1mono_ZC60_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC60_R_ALT_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_ALT,ALT,Naive_THP1mono_ZC60_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC60_R_REF_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_REF,REF,Naive_THP1mono_ZC60_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC60_R_REF_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_REF,REF,Naive_THP1mono_ZC60_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC60_R_REF_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_REF,REF,Naive_THP1mono_ZC60_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC60_R_REF_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_REF,REF,Naive_THP1mono_ZC60_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC60_R_REF_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC60_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_REF,REF,Naive_THP1mono_ZC60_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC90_R_ALT_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_ALT,ALT,Naive_THP1mono_ZC90_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC90_R_ALT_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_ALT,ALT,Naive_THP1mono_ZC90_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC90_R_ALT_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_ALT,ALT,Naive_THP1mono_ZC90_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC90_R_ALT_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_ALT,ALT,Naive_THP1mono_ZC90_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC90_R_ALT_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_ALT,ALT,Naive_THP1mono_ZC90_R_ALT,Monocyte_ALT,THP1_Monocyte_ALT
Naive_THP1mono_ZC90_R_REF_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1_REF,REF,Naive_THP1mono_ZC90_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC90_R_REF_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2_REF,REF,Naive_THP1mono_ZC90_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC90_R_REF_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3_REF,REF,Naive_THP1mono_ZC90_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC90_R_REF_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4_REF,REF,Naive_THP1mono_ZC90_R_REF,Monocyte_REF,THP1_Monocyte_REF
Naive_THP1mono_ZC90_R_REF_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5_REF,REF,Naive_THP1mono_ZC90_R_REF,Monocyte_REF,THP1_Monocyte_REF

In [10]:
#Expand 5 annotation, GutR1R2merged20240404
expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_GutR1R2merged.csv', 
    save_path='annotation_barcodes/mpra3_annot_GutR1R2merged20240404_barcodes.csv')

import pandas as pd
#Split annotation
GutR1R2merged20240404 = pd.read_csv('annotation_barcodes/mpra3_annot_GutR1R2merged20240404_barcodes.csv',index_col=0)

GutR1R2merged20240404[GutR1R2merged20240404["SI"]==1].to_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_SI_barcodes.csv")
GutR1R2merged20240404[GutR1R2merged20240404["LI"]==1].to_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_LI_barcodes.csv")

#Split barcodes according to annotation
import pandas as pd
GutR1R2merged20240404_barcodes = pd.read_csv("read_counts_R1R2/GutR1R2merged20240404_DNA_matched_barcodes_reshaped.csv",index_col=0)
GutR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_SI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged20240404_SI_DNA_matched_barcodes_reshaped.csv")
GutR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_LI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged20240404_LI_DNA_matched_barcodes_reshaped.csv")


GutR1R2merged20240404_barcodes = pd.read_csv("read_counts_R1R2/GutR1R2merged20240404_RNA_matched_barcodes_reshaped.csv",index_col=0)
GutR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_SI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged20240404_SI_RNA_matched_barcodes_reshaped.csv")
GutR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_LI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged20240404_LI_RNA_matched_barcodes_reshaped.csv")


#GutR1R2merged20240404 Interaction
import pandas as pd
GutR1R2merged20240404_annotation = pd.read_csv('annotation_barcodes/mpra3_annot_GutR1R2merged20240404_barcodes.csv',index_col=0)
GutR1R2merged20240404_annotation['Allele'] = GutR1R2merged20240404_annotation['Allele_String'].map({'ALT': 1, 'REF': 0})
GutR1R2merged20240404_annotation["SI_interaction"] = GutR1R2merged20240404_annotation["SI"] * GutR1R2merged20240404_annotation["Allele"]
GutR1R2merged20240404_annotation["LI_interaction"] = GutR1R2merged20240404_annotation["LI"] * GutR1R2merged20240404_annotation["Allele"]

GutR1R2merged20240404_annotation.to_csv('annotation_barcodes/mpra3_annot_GutR1R2merged20240404_barcodes_interaction.csv')

GutR1R2merged20240404 = pd.read_csv('annotation_barcodes/mpra3_annot_GutR1R2merged20240404_barcodes_interaction.csv',index_col=0)
GutR1R2merged20240404[(GutR1R2merged20240404["SI"]==1) | (GutR1R2merged20240404["LI"]==1)].to_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_SIvsLI_barcodes.csv")


#Split barcodes according to annotation
import pandas as pd
GutR1R2merged20240404_barcodes = pd.read_csv("read_counts_R1R2/GutR1R2merged20240404_DNA_matched_barcodes_reshaped.csv",index_col=0)
GutR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_SIvsLI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged20240404_SIvsLI_DNA_matched_barcodes_reshaped.csv")

#Split barcodes according to annotation
import pandas as pd
GutR1R2merged20240404_barcodes = pd.read_csv("read_counts_R1R2/GutR1R2merged20240404_RNA_matched_barcodes_reshaped.csv",index_col=0)
GutR1R2merged20240404_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged20240404_SIvsLI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged20240404_SIvsLI_RNA_matched_barcodes_reshaped.csv")

In [16]:
#Making THP1Macrophage
import pandas as pd
df_DNA_IFNB = pd.read_csv("read_counts_R1R2/THP1_IFNB_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_IFNB = pd.read_csv("read_counts_R1R2/THP1_IFNB_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_IFNG = pd.read_csv("read_counts_R1R2/THP1_IFNG_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_IFNG = pd.read_csv("read_counts_R1R2/THP1_IFNG_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_LPSIFNG = pd.read_csv("read_counts_R1R2/THP1_LPSIFNG_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_LPSIFNG = pd.read_csv("read_counts_R1R2/THP1_LPSIFNG_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_Naive = pd.read_csv("read_counts_R1R2/THP1_Naive_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_Naive = pd.read_csv("read_counts_R1R2/THP1_Naive_RNA_matched_barcodes_reshaped.csv", index_col=0)
pd.concat([df_DNA_IFNB,df_DNA_IFNG,df_DNA_LPSIFNG,df_DNA_Naive],axis=1).to_csv("read_counts_R1R2/THP1Macrophage_DNA_matched_barcodes_reshaped.csv")
pd.concat([df_RNA_IFNB,df_RNA_IFNG,df_RNA_LPSIFNG,df_RNA_Naive],axis=1).to_csv("read_counts_R1R2/THP1Macrophage_RNA_matched_barcodes_reshaped.csv")
annot_IFNB = pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNB_barcodes.csv",index_col=0)
annot_IFNG = pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNG_barcodes.csv",index_col=0)
annot_LPSIFNG = pd.read_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNG_barcodes.csv",index_col=0)
annot_Naive = pd.read_csv("annotation_barcodes/mpra3_annot_THP1_Naive_barcodes.csv",index_col=0)
pd.concat([annot_IFNB,annot_IFNG,annot_LPSIFNG,annot_Naive],axis=0).to_csv("annotation_barcodes/mpra3_annot_THP1Macrophage_barcodes.csv")

#Combine brain regions
import pandas as pd
df_DNA_ctx = pd.read_csv("read_counts_R1R2/Brain_Cortex_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_ctx = pd.read_csv("read_counts_R1R2/Brain_Cortex_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_hipo = pd.read_csv("read_counts_R1R2/Brain_Hippocampus_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_hipo = pd.read_csv("read_counts_R1R2/Brain_Hippocampus_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_str = pd.read_csv("read_counts_R1R2/Brain_Striatum_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_str = pd.read_csv("read_counts_R1R2/Brain_Striatum_RNA_matched_barcodes_reshaped.csv", index_col=0)
pd.concat([df_DNA_ctx,df_DNA_hipo,df_DNA_str],axis=1).to_csv("read_counts_R1R2/Brain_DNA_matched_barcodes_reshaped.csv")
pd.concat([df_RNA_ctx,df_RNA_hipo,df_RNA_str],axis=1).to_csv("read_counts_R1R2/Brain_RNA_matched_barcodes_reshaped.csv")
annot_ctx = pd.read_csv("annotation_barcodes/mpra3_annot_Brain_Cortex_barcodes.csv",index_col=0)
annot_hipo = pd.read_csv("annotation_barcodes/mpra3_annot_Brain_Hippocampus_barcodes.csv",index_col=0)
annot_str = pd.read_csv("annotation_barcodes/mpra3_annot_Brain_Striatum_barcodes.csv",index_col=0)
pd.concat([annot_ctx,annot_hipo,annot_str],axis=0).to_csv("annotation_barcodes/mpra3_annot_Brain_barcodes.csv")

#Combine HMC3 regions
import pandas as pd
df_DNA_IFNB = pd.read_csv("read_counts_R1R2/HMC3_IFNB_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_IFNB = pd.read_csv("read_counts_R1R2/HMC3_IFNB_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_IFNG = pd.read_csv("read_counts_R1R2/HMC3_IFNG_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_IFNG = pd.read_csv("read_counts_R1R2/HMC3_IFNG_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_LPSIFNG = pd.read_csv("read_counts_R1R2/HMC3_LPSIFNG_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_LPSIFNG = pd.read_csv("read_counts_R1R2/HMC3_LPSIFNG_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_Naive = pd.read_csv("read_counts_R1R2/HMC3_Naive_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_Naive = pd.read_csv("read_counts_R1R2/HMC3_Naive_RNA_matched_barcodes_reshaped.csv", index_col=0)

pd.concat([df_DNA_IFNB,df_DNA_IFNG,df_DNA_LPSIFNG,df_DNA_Naive],axis=1).to_csv("read_counts_R1R2/HMC3_DNA_matched_barcodes_reshaped.csv")
pd.concat([df_RNA_IFNB,df_RNA_IFNG,df_RNA_LPSIFNG,df_RNA_Naive],axis=1).to_csv("read_counts_R1R2/HMC3_RNA_matched_barcodes_reshaped.csv")

annot_IFNB = pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNB_barcodes.csv",index_col=0)
annot_IFNG = pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNG_barcodes.csv",index_col=0)
annot_LPSIFNG = pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNG_barcodes.csv",index_col=0)
annot_Naive = pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_Naive_barcodes.csv",index_col=0)
pd.concat([annot_IFNB,annot_IFNG,annot_LPSIFNG,annot_Naive],axis=0).to_csv("annotation_barcodes/mpra3_annot_HMC3_barcodes.csv")

In [15]:
#Brain vs HEK293T
import pandas as pd
df_DNA_Brain = pd.read_csv("read_counts_R1R2/BrainR1R2merged_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_DNA_HEK293T = pd.read_csv("read_counts_R1R2/HEK293T_DNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_Brain = pd.read_csv("read_counts_R1R2/BrainR1R2merged_RNA_matched_barcodes_reshaped.csv", index_col=0)
df_RNA_HEK293T = pd.read_csv("read_counts_R1R2/HEK293T_RNA_matched_barcodes_reshaped.csv", index_col=0)
pd.concat([df_DNA_Brain,df_DNA_HEK293T],axis=1).to_csv("read_counts_R1R2/BrainR1R2mergedvsHEK293T_DNA_matched_barcodes_reshaped.csv")
pd.concat([df_RNA_Brain,df_RNA_HEK293T],axis=1).to_csv("read_counts_R1R2/BrainR1R2mergedvsHEK293T_RNA_matched_barcodes_reshaped.csv")
annot_Brain = pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged_barcodes.csv",index_col=0)
annot_HEK293T = pd.read_csv("annotation_barcodes/mpra3_annot_HEK293T_barcodes.csv",index_col=0)

df_brain_hek293t =  pd.concat([annot_Brain,annot_HEK293T],axis=0)
df_brain_hek293t['Allele'] = df_brain_hek293t['Allele_String'].map({'ALT': 1, 'REF': 0})
df_brain_hek293t['Brain'] = df_brain_hek293t['Parent'].map({'Brain': 1, 'HEK293T': 0})
df_brain_hek293t["Brain_interaction"] = df_brain_hek293t["Brain"] * df_brain_hek293t["Allele"]
df_brain_hek293t.to_csv("annotation_barcodes/mpra3_annot_BrainR1R2mergedvsHEK293T_barcodes.csv")

In [7]:
import pandas as pd
THP1_RNA = pd.read_csv("read_counts_R1R2/THP1Macrophage_RNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_DNA = pd.read_csv("read_counts_R1R2/THP1Macrophage_DNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_RNA = pd.read_csv("read_counts_R1R2/HMC3_RNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_DNA = pd.read_csv("read_counts_R1R2/HMC3_DNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_annotation = pd.read_csv("annotation_barcodes/mpra3_annot_THP1Macrophage_barcodes.csv",index_col=0)
HMC3_annotation = pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_barcodes_interaction.csv",index_col=0)
pd.concat([THP1_RNA,HMC3_RNA],axis=1).to_csv("read_counts_R1R2/THP1MacrophagevsHMC3_RNA_matched_barcodes_reshaped.csv")
pd.concat([THP1_DNA,HMC3_DNA],axis=1).to_csv("read_counts_R1R2/THP1MacrophagevsHMC3_DNA_matched_barcodes_reshaped.csv")
pd.concat([THP1_annotation,HMC3_annotation],axis=0).to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagevsHMC3_barcodes.csv")

import pandas as pd
THP1_RNA = pd.read_csv("read_counts_R1R2/THP1_LPSIFNGvsNaive_RNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_DNA = pd.read_csv("read_counts_R1R2/THP1_LPSIFNGvsNaive_DNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_RNA = pd.read_csv("read_counts_R1R2/HMC3_LPSIFNGvsNaive_RNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_DNA = pd.read_csv("read_counts_R1R2/HMC3_LPSIFNGvsNaive_DNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_annotation = pd.read_csv("annotation_barcodes/mpra3_annot_THP1_LPSIFNGvsNaive_barcodes.csv",index_col=0)
HMC3_annotation = pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_LPSIFNGvsNaive_barcodes.csv",index_col=0)
pd.concat([THP1_RNA,HMC3_RNA],axis=1).to_csv("read_counts_R1R2/THP1MacrophageHMC3_LPSIFNGvsNaive_RNA_matched_barcodes_reshaped.csv")
pd.concat([THP1_DNA,HMC3_DNA],axis=1).to_csv("read_counts_R1R2/THP1MacrophageHMC3_LPSIFNGvsNaive_DNA_matched_barcodes_reshaped.csv")
pd.concat([THP1_annotation,HMC3_annotation],axis=0).to_csv("annotation_barcodes/mpra3_annot_THP1MacrophageHMC3_LPSIFNGvsNaive_barcodes.csv")

import pandas as pd
THP1_RNA = pd.read_csv("read_counts_R1R2/THP1_IFNGvsNaive_RNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_DNA = pd.read_csv("read_counts_R1R2/THP1_IFNGvsNaive_DNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_RNA = pd.read_csv("read_counts_R1R2/HMC3_IFNGvsNaive_RNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_DNA = pd.read_csv("read_counts_R1R2/HMC3_IFNGvsNaive_DNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_annotation = pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNGvsNaive_barcodes.csv",index_col=0)
HMC3_annotation = pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNGvsNaive_barcodes.csv",index_col=0)
pd.concat([THP1_RNA,HMC3_RNA],axis=1).to_csv("read_counts_R1R2/THP1MacrophageHMC3_IFNGvsNaive_RNA_matched_barcodes_reshaped.csv")
pd.concat([THP1_DNA,HMC3_DNA],axis=1).to_csv("read_counts_R1R2/THP1MacrophageHMC3_IFNGvsNaive_DNA_matched_barcodes_reshaped.csv")
pd.concat([THP1_annotation,HMC3_annotation],axis=0).to_csv("annotation_barcodes/mpra3_annot_THP1MacrophageHMC3_IFNGvsNaive_barcodes.csv")

import pandas as pd
THP1_RNA = pd.read_csv("read_counts_R1R2/THP1_IFNBvsNaive_RNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_DNA = pd.read_csv("read_counts_R1R2/THP1_IFNBvsNaive_DNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_RNA = pd.read_csv("read_counts_R1R2/HMC3_IFNBvsNaive_RNA_matched_barcodes_reshaped.csv",index_col=0)
HMC3_DNA = pd.read_csv("read_counts_R1R2/HMC3_IFNBvsNaive_DNA_matched_barcodes_reshaped.csv",index_col=0)
THP1_annotation = pd.read_csv("annotation_barcodes/mpra3_annot_THP1_IFNBvsNaive_barcodes.csv",index_col=0)
HMC3_annotation = pd.read_csv("annotation_barcodes/mpra3_annot_HMC3_IFNBvsNaive_barcodes.csv",index_col=0)
pd.concat([THP1_RNA,HMC3_RNA],axis=1).to_csv("read_counts_R1R2/THP1MacrophageHMC3_IFNBvsNaive_RNA_matched_barcodes_reshaped.csv")
pd.concat([THP1_DNA,HMC3_DNA],axis=1).to_csv("read_counts_R1R2/THP1MacrophageHMC3_IFNBvsNaive_DNA_matched_barcodes_reshaped.csv")
pd.concat([THP1_annotation,HMC3_annotation],axis=0).to_csv("annotation_barcodes/mpra3_annot_THP1MacrophageHMC3_IFNBvsNaive_barcodes.csv")

In [6]:
#Expand 32 annotation, GutR1R2merged
expand_annotation_32barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_GutR1R2merged.csv', 
    save_path='annotation_barcodes/mpra3_annot_GutR1R2merged_barcodes.csv')

import pandas as pd
#Split annotation
GutR1R2merged = pd.read_csv('annotation_barcodes/mpra3_annot_GutR1R2merged_barcodes.csv',index_col=0)

GutR1R2merged[GutR1R2merged["SI"]==1].to_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_SI_barcodes.csv")
GutR1R2merged[GutR1R2merged["LI"]==1].to_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_LI_barcodes.csv")

#Split barcodes according to annotation
import pandas as pd
GutR1R2merged_barcodes = pd.read_csv("read_counts_R1R2/GutR1R2merged20240326_DNA_matched_barcodes_reshaped.csv",index_col=0)
GutR1R2merged_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_SI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged_SI_DNA_matched_barcodes_reshaped.csv")
GutR1R2merged_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_LI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged_LI_DNA_matched_barcodes_reshaped.csv")


GutR1R2merged_barcodes = pd.read_csv("read_counts_R1R2/GutR1R2merged20240326_RNA_matched_barcodes_reshaped.csv",index_col=0)
GutR1R2merged_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_SI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged_SI_RNA_matched_barcodes_reshaped.csv")
GutR1R2merged_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_LI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged_LI_RNA_matched_barcodes_reshaped.csv")


#GutR1R2merged Interaction
import pandas as pd
GutR1R2merged_annotation = pd.read_csv('annotation_barcodes/mpra3_annot_GutR1R2merged_barcodes.csv',index_col=0)
GutR1R2merged_annotation['Allele'] = GutR1R2merged_annotation['Allele_String'].map({'ALT': 1, 'REF': 0})
GutR1R2merged_annotation["SI_interaction"] = GutR1R2merged_annotation["SI"] * GutR1R2merged_annotation["Allele"]
GutR1R2merged_annotation["LI_interaction"] = GutR1R2merged_annotation["LI"] * GutR1R2merged_annotation["Allele"]

GutR1R2merged_annotation.to_csv('annotation_barcodes/mpra3_annot_GutR1R2merged_barcodes_interaction.csv')

GutR1R2merged = pd.read_csv('annotation_barcodes/mpra3_annot_GutR1R2merged_barcodes_interaction.csv',index_col=0)
GutR1R2merged[(GutR1R2merged["SI"]==1) | (GutR1R2merged["LI"]==1)].to_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_SIvsLI_barcodes.csv")


#Split barcodes according to annotation
import pandas as pd
GutR1R2merged_barcodes = pd.read_csv("read_counts_R1R2/GutR1R2merged20240326_DNA_matched_barcodes_reshaped.csv",index_col=0)
GutR1R2merged_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_SIvsLI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged_SIvsLI_DNA_matched_barcodes_reshaped.csv")

#Split barcodes according to annotation
import pandas as pd
GutR1R2merged_barcodes = pd.read_csv("read_counts_R1R2/GutR1R2merged20240326_RNA_matched_barcodes_reshaped.csv",index_col=0)
GutR1R2merged_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_GutR1R2merged_SIvsLI_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/GutR1R2merged_SIvsLI_RNA_matched_barcodes_reshaped.csv")

# Brain vs Immune

In [98]:
#Expand 32 annotation
expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_THP1Macrophage.csv', 
    save_path='annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_barcodes.csv')

#THP1MacrophagePseudobarcodes Interaction
import pandas as pd
THP1MacrophagePseudobarcodes_annotation = pd.read_csv('annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_barcodes.csv',index_col=0)

THP1MacrophagePseudobarcodes_annotation['Allele'] = THP1MacrophagePseudobarcodes_annotation['Allele_String'].map({'ALT': 1, 'REF': 0})
THP1MacrophagePseudobarcodes_annotation["IFNB_interaction"] = THP1MacrophagePseudobarcodes_annotation["IFNB"] * THP1MacrophagePseudobarcodes_annotation["Allele"]
THP1MacrophagePseudobarcodes_annotation["IFNG_interaction"] = THP1MacrophagePseudobarcodes_annotation["IFNG"] * THP1MacrophagePseudobarcodes_annotation["Allele"]
THP1MacrophagePseudobarcodes_annotation["LPSIFNG_interaction"] = THP1MacrophagePseudobarcodes_annotation["LPSIFNG"] * THP1MacrophagePseudobarcodes_annotation["Allele"]
THP1MacrophagePseudobarcodes_annotation["Naive_interaction"] = THP1MacrophagePseudobarcodes_annotation["Naive_Macrophage"] * THP1MacrophagePseudobarcodes_annotation["Allele"]
THP1MacrophagePseudobarcodes_annotation.to_csv('annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_barcodes_interaction.csv')

#Split annotation
THP1MacrophagePseudobarcodes = pd.read_csv('annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_barcodes_interaction.csv',index_col=0)
THP1MacrophagePseudobarcodes[THP1MacrophagePseudobarcodes["IFNB"]==1].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNB_barcodes.csv")
THP1MacrophagePseudobarcodes[THP1MacrophagePseudobarcodes["IFNG"]==1].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNG_barcodes.csv")
THP1MacrophagePseudobarcodes[THP1MacrophagePseudobarcodes["LPSIFNG"]==1].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNG_barcodes.csv")
THP1MacrophagePseudobarcodes[THP1MacrophagePseudobarcodes["Naive_Macrophage"]==1].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_Naive_barcodes.csv")
THP1MacrophagePseudobarcodes[THP1MacrophagePseudobarcodes["Tissue"]=="THP1MacrophagePseudobarcodes_Monocyte"].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_Monocyte_barcodes.csv")

THP1MacrophagePseudobarcodes = pd.read_csv('annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_barcodes_interaction.csv',index_col=0)
THP1MacrophagePseudobarcodes[(THP1MacrophagePseudobarcodes["IFNB"]==1) | (THP1MacrophagePseudobarcodes["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNBvsNaive_barcodes.csv")
THP1MacrophagePseudobarcodes[(THP1MacrophagePseudobarcodes["IFNG"]==1) | (THP1MacrophagePseudobarcodes["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNGvsNaive_barcodes.csv")
THP1MacrophagePseudobarcodes[(THP1MacrophagePseudobarcodes["LPSIFNG"]==1) | (THP1MacrophagePseudobarcodes["Naive_Macrophage"]==1)].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNGvsNaive_barcodes.csv")
THP1MacrophagePseudobarcodes[(THP1MacrophagePseudobarcodes["LPSIFNG"]==1) | (THP1MacrophagePseudobarcodes["IFNG"]==1)].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNGvsIFNG_barcodes.csv")
THP1MacrophagePseudobarcodes[(THP1MacrophagePseudobarcodes["Tissue"]=="THP1MacrophagePseudobarcodes_Monocyte") | (THP1MacrophagePseudobarcodes["Tissue"]=="THP1MacrophagePseudobarcodes_Naive")].to_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_MacrophagevsMonocyte_barcodes.csv")

#Split barcodes according to annotation
import pandas as pd
THP1MacrophagePseudobarcodes_barcodes = pd.read_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_DNA_matched_barcodes_reshaped.csv",index_col=0)
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNB_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_IFNB_DNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_IFNG_DNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_LPSIFNG_DNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_Naive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_Naive_DNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_Monocyte_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_Monocyte_DNA_matched_barcodes_reshaped.csv")

THP1MacrophagePseudobarcodes_barcodes = pd.read_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_RNA_matched_barcodes_reshaped.csv",index_col=0)
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNB_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_IFNB_RNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_IFNG_RNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_LPSIFNG_RNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_Naive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_Naive_RNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_Monocyte_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_Monocyte_RNA_matched_barcodes_reshaped.csv")


#Split barcodes according to annotation
import pandas as pd
THP1MacrophagePseudobarcodes_barcodes = pd.read_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_DNA_matched_barcodes_reshaped.csv",index_col=0)
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNBvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_IFNBvsNaive_DNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_IFNGvsNaive_DNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_LPSIFNGvsNaive_DNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNGvsIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_LPSIFNGvsIFNG_DNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_MacrophagevsMonocyte_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_MacrophagevsMonocyte_DNA_matched_barcodes_reshaped.csv")

#Split barcodes according to annotation
import pandas as pd
THP1MacrophagePseudobarcodes_barcodes = pd.read_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_RNA_matched_barcodes_reshaped.csv",index_col=0)
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNBvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_IFNBvsNaive_RNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_IFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_IFNGvsNaive_RNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNGvsNaive_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_LPSIFNGvsNaive_RNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_LPSIFNGvsIFNG_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_LPSIFNGvsIFNG_RNA_matched_barcodes_reshaped.csv")
THP1MacrophagePseudobarcodes_barcodes[pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_MacrophagevsMonocyte_barcodes.csv",index_col=0).index].to_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_MacrophagevsMonocyte_RNA_matched_barcodes_reshaped.csv")

In [99]:
import pandas as pd

In [100]:
df_brain = pd.read_csv("read_counts_R1R2/BrainR1R2merged20240404_RNA_matched_barcodes_reshaped.csv",index_col=0)
df_mac = pd.read_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_RNA_matched_barcodes_reshaped.csv",index_col=0)
columns_to_drop = df_mac.columns[df_mac.columns.str.endswith(tuple([str(i) for i in range(16,33)]))]
df_mac = df_mac.drop(columns=columns_to_drop)
pd.merge(df_mac,df_brain,left_index=True,right_index=True).to_csv("read_counts_R1R2/THP1MacrophageBrainR1R2merged20240404_RNA_matched_barcodes_reshaped.csv")

In [101]:
df_brain = pd.read_csv("read_counts_R1R2/BrainR1R2merged20240404_DNA_matched_barcodes_reshaped.csv",index_col=0)
df_mac = pd.read_csv("read_counts_R1R2/THP1MacrophagePseudobarcodes_DNA_matched_barcodes_reshaped.csv",index_col=0)
columns_to_drop = df_mac.columns[df_mac.columns.str.endswith(tuple([str(i) for i in range(16,33)]))]
df_mac = df_mac.drop(columns=columns_to_drop)
pd.merge(df_mac,df_brain,left_index=True,right_index=True).to_csv("read_counts_R1R2/THP1MacrophageBrainR1R2merged20240404_DNA_matched_barcodes_reshaped.csv")

In [102]:

df_brain = pd.read_csv("annotation_barcodes/mpra3_annot_BrainR1R2merged20240404_barcodes_interaction.csv",index_col=0)

df_mac = pd.read_csv("annotation_barcodes/mpra3_annot_THP1MacrophagePseudobarcodes_barcodes.csv",index_col=0)
index_to_drop = df_mac.index[df_mac.index.str.endswith(tuple([str(i) for i in range(16,33)]))]
df_mac = df_mac.drop(index=index_to_drop)
df_mac_brain = pd.concat([df_mac,df_brain])
df_mac_brain['Parent_Allele'] = df_mac_brain["Parent"] + "_" + df_mac_brain["Allele_String"]
df_mac_brain["Brain_interaction"] = 0
# Select rows where 'Parent_Allele' is 'Brain_ALT' and set the 'Brain_interaction' column to 1
df_mac_brain.loc[df_mac_brain['Parent_Allele'] == "Brain_ALT", "Brain_interaction"] = 1
df_mac_brain.to_csv("annotation_barcodes/mpra3_annot_THP1Macrophage_barcodesBrainR1R2merged20240404.csv")

In [115]:
from scipy.stats import spearmanr
from scipy.stats import pearsonr
# Assuming you have two arrays or lists of data, let's call them X and Y
X = pd.read_csv("allele_differences_withoutcontrol/20240129_comparative_THP1Macrophage_allele.csv",index_col=0)['logFC']
Y = pd.read_csv("20240417_comparative_THP1Pseudobarcodes_allele.csv",index_col=0)['logFC']

# Calculate Spearman correlation coefficient
correlation_coefficient, p_value = spearmanr(X, Y)

print("Spearman correlation coefficient:", correlation_coefficient)
print("p-value:", p_value)

Spearman correlation coefficient: 0.982253566380275
p-value: 0.0

# Motif-Allele Comparison

In [1]:
import pandas as pd
def expand_annotation_15barcodes_from_enhancer_annotation(enhancer_annotation_path, save_path):
    df = pd.read_csv(enhancer_annotation_path,index_col=0)
    # Assuming 'df' is your original DataFrame
    # Duplicate the DataFrame
    duplicated_df = pd.concat([df, df,df,df,df]).sort_index(kind='merge')

    # Create an alternating index
    new_index = []
    for i, index in enumerate(duplicated_df.index):
        if i % 5 == 0:
            new_index.append(f"{index}_motif")
        elif i%5 == 1:
            new_index.append(f"{index}_ref")
        elif i%5 == 2:
            new_index.append(f"{index}_alt1")
        elif i%5 == 3:
            new_index.append(f"{index}_alt2")
        elif i%5 == 4:
            new_index.append(f"{index}_alt3")

    # Assign the new index to the DataFrame
    duplicated_df.index = new_index

    # Now duplicated_df has each row duplicated with alternating "_ALT" and "_REF" suffixes in the index
    df = duplicated_df

    # Expand dataframe to have 32 rows for each original row
    expanded_df = pd.DataFrame()

    for _, row in df.iterrows():
        for i in range(1, 16):
            new_row = row.copy()
            new_row['Barcode_number'] = i
            expanded_df = pd.concat([expanded_df, new_row], axis=1)
    expanded_df = expanded_df.T
    expanded_df["sample_barcodes"] = (expanded_df.index + "_Barcode_" + expanded_df["Barcode_number"].astype(str)).tolist()

    expanded_df["Barcode_Allele"] = expanded_df["Barcode_number"].astype(str) + expanded_df.index.str.slice(-4,)
    

    expanded_df["Allele_String"] = expanded_df.index.str.slice(-3,)
    expanded_df["Test_Allele"] = expanded_df["Test"]+"_"+expanded_df["Allele_String"]
    expanded_df["Animal_Allele"] = expanded_df["Animal"]+"_"+expanded_df["Allele_String"]
    expanded_df["Tissue_Allele"] = expanded_df["Tissue"]+"_"+expanded_df["Allele_String"]
    #expanded_df = expanded_df.reset_index()
    expanded_df = expanded_df.set_index("sample_barcodes")
    expanded_df.rename(columns={"index": "sample_allele"}, inplace=True)
    expanded_df.index.name = None
    expanded_df['Motif_Allele'] = expanded_df['Allele_String'].apply(lambda x: "motif" if "tif" in x else "Allele")

    if save_path:
        expanded_df.to_csv(save_path)
    return expanded_df

In [2]:
#Expand 15 anootation HEK293T
expand_annotation_15barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_HEK293T.csv', 
    save_path='annotation_barcodes/mpra3_annot_HEK293T_barcodes_motif.csv')

expand_annotation_15barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_HMC3.csv', 
    save_path='annotation_barcodes/mpra3_annot_HMC3_barcodes_motif.csv')
HMC3_barcodes = pd.read_csv("read_counts_R1R2/HMC3_DNA_matched_barcodes_reshaped_motif.csv",index_col=0)
HMC3_barcodes[pd.read_csv('annotation_barcodes/mpra3_annot_HMC3_barcodes_motif.csv',index_col=0).index].to_csv("read_counts_R1R2/HMC3_DNA_matched_barcodes_reshaped_motif.csv")
HMC3_barcodes = pd.read_csv("read_counts_R1R2/HMC3_RNA_matched_barcodes_reshaped_motif.csv",index_col=0)
HMC3_barcodes[pd.read_csv('annotation_barcodes/mpra3_annot_HMC3_barcodes_motif.csv',index_col=0).index].to_csv("read_counts_R1R2/HMC3_RNA_matched_barcodes_reshaped_motif.csv")

expand_annotation_15barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_THP1Macrophage.csv', 
    save_path='annotation_barcodes/mpra3_annot_THP1Macrophage_barcodes_motif.csv')
THP1_barcodes = pd.read_csv("read_counts_R1R2/THP1_DNA_matched_barcodes_reshaped_motif.csv",index_col=0)
THP1_barcodes[pd.read_csv('annotation_barcodes/mpra3_annot_THP1Macrophage_barcodes_motif.csv',index_col=0).index].to_csv("read_counts_R1R2/THP1Macrophage_DNA_matched_barcodes_reshaped_motif.csv")
THP1_barcodes = pd.read_csv("read_counts_R1R2/THP1_RNA_matched_barcodes_reshaped_motif.csv",index_col=0)
THP1_barcodes[pd.read_csv('annotation_barcodes/mpra3_annot_THP1Macrophage_barcodes_motif.csv',index_col=0).index].to_csv("read_counts_R1R2/THP1Macrophage_RNA_matched_barcodes_reshaped_motif.csv")

In [6]:
import pandas as pd
def expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path, save_path):
    df = pd.read_csv(enhancer_annotation_path,index_col=0)
    # Assuming 'df' is your original DataFrame
    # Duplicate the DataFrame
    duplicated_df = pd.concat([df, df,df,df,df]).sort_index(kind='merge')

    # Create an alternating index
    new_index = []
    for i, index in enumerate(duplicated_df.index):
        if i % 5 == 0:
            new_index.append(f"{index}_motif")
        elif i%5 == 1:
            new_index.append(f"{index}_ref")
        elif i%5 == 2:
            new_index.append(f"{index}_alt1")
        elif i%5 == 3:
            new_index.append(f"{index}_alt2")
        elif i%5 == 4:
            new_index.append(f"{index}_alt3")

    # Assign the new index to the DataFrame
    duplicated_df.index = new_index

    # Now duplicated_df has each row duplicated with alternating "_ALT" and "_REF" suffixes in the index
    df = duplicated_df

    # Expand dataframe to have 32 rows for each original row
    expanded_df = pd.DataFrame()

    for _, row in df.iterrows():
        for i in range(1, 6):
            new_row = row.copy()
            new_row['Barcode_number'] = i
            expanded_df = pd.concat([expanded_df, new_row], axis=1)
    expanded_df = expanded_df.T
    expanded_df["sample_barcodes"] = (expanded_df.index + "_Barcode_" + expanded_df["Barcode_number"].astype(str)).tolist()

    expanded_df["Barcode_Allele"] = expanded_df["Barcode_number"].astype(str) + expanded_df.index.str.slice(-4,)
    

    expanded_df["Allele_String"] = expanded_df.index.str.slice(-3,)
    expanded_df["Test_Allele"] = expanded_df["Test"]+"_"+expanded_df["Allele_String"]
    expanded_df["Animal_Allele"] = expanded_df["Animal"]+"_"+expanded_df["Allele_String"]
    expanded_df["Tissue_Allele"] = expanded_df["Tissue"]+"_"+expanded_df["Allele_String"]
    #expanded_df = expanded_df.reset_index()
    expanded_df = expanded_df.set_index("sample_barcodes")
    expanded_df.rename(columns={"index": "sample_allele"}, inplace=True)
    expanded_df.index.name = None
    expanded_df['Motif_Allele'] = expanded_df['Allele_String'].apply(lambda x: "motif" if "tif" in x else "Allele")

    if save_path:
        expanded_df.to_csv(save_path)
    return expanded_df

In [8]:
expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_THP1Monocyte.csv', 
    save_path='annotation_barcodes/mpra3_annot_THP1Monocyte_barcodes_motif.csv')
expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_BrainR1R2merged.csv', 
    save_path='annotation_barcodes/mpra3_annot_BrainR1R2merged_barcodes_motif.csv')
expand_annotation_5barcodes_from_enhancer_annotation(enhancer_annotation_path='annotation_enhancer/mpra3_annot_GutR1R2merged.csv', 
    save_path='annotation_barcodes/mpra3_annot_GutR1R2merged_barcodes_motif.csv')

,Tissue,Delivery,Date,Animal,Test,Function,Parent,IFNB,IFNG,LPSIFNG,Naive_Macrophage,THP1_Monocytes,Barcode_number,Barcode_Allele,Allele_String,Test_Allele,Animal_Allele,Tissue_Allele,Motif_Allele
Naive_THP1mono_ZC111_R_motif_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1otif,tif,Naive_THP1mono_ZC111_R_tif,Monocyte_tif,THP1_Monocyte_tif,motif
Naive_THP1mono_ZC111_R_motif_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2otif,tif,Naive_THP1mono_ZC111_R_tif,Monocyte_tif,THP1_Monocyte_tif,motif
Naive_THP1mono_ZC111_R_motif_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3otif,tif,Naive_THP1mono_ZC111_R_tif,Monocyte_tif,THP1_Monocyte_tif,motif
Naive_THP1mono_ZC111_R_motif_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4otif,tif,Naive_THP1mono_ZC111_R_tif,Monocyte_tif,THP1_Monocyte_tif,motif
Naive_THP1mono_ZC111_R_motif_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC111_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5otif,tif,Naive_THP1mono_ZC111_R_tif,Monocyte_tif,THP1_Monocyte_tif,motif
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Naive_THP1mono_ZC90_R_alt3_Barcode_1,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,1,1alt3,lt3,Naive_THP1mono_ZC90_R_lt3,Monocyte_lt3,THP1_Monocyte_lt3,Allele
Naive_THP1mono_ZC90_R_alt3_Barcode_2,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,2,2alt3,lt3,Naive_THP1mono_ZC90_R_lt3,Monocyte_lt3,THP1_Monocyte_lt3,Allele
Naive_THP1mono_ZC90_R_alt3_Barcode_3,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,3,3alt3,lt3,Naive_THP1mono_ZC90_R_lt3,Monocyte_lt3,THP1_Monocyte_lt3,Allele
Naive_THP1mono_ZC90_R_alt3_Barcode_4,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,4,4alt3,lt3,Naive_THP1mono_ZC90_R_lt3,Monocyte_lt3,THP1_Monocyte_lt3,Allele
Naive_THP1mono_ZC90_R_alt3_Barcode_5,THP1_Monocyte,Nucleofector,NaN,Monocyte,Naive_THP1mono_ZC90_R,Immune,THP1_Monocyte,0,0,0,0,1,5,5alt3,lt3,Naive_THP1mono_ZC90_R_lt3,Monocyte_lt3,THP1_Monocyte_lt3,Allele