In [52]:
import pandas as pd
df_alref = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/read_counts_R1R2/BrainR1R2merged20240404_DNA_matched_barcodes_reshaped_altref.csv' ,index_col=0)
df_alref 
df = pd.read_csv("indexing/AD_MPRA_2_7_Contributor_20230213_unique_GeneName_uniqueEnhancer_id.csv").drop_duplicates(['enhancer_id'])
df = df[df['enhancer_id'].isin(df_alref.index)]
def calculate_gc_content(seq):
    # Calculate the number of G's and C's in the sequence
    seq=seq.upper()
    gc_count = seq.count('G') + seq.count('C')
    # Calculate GC content as a percentage of the total sequence length
    return (gc_count / len(seq)) * 100 if len(seq) > 0 else 0
df

,enhancer_seq,enhancer_id,RSID,Contributor,nearest_gene
1,GCGCTCACCTTTGGCCTTGTCTTTTCGCCACCGCCGGCGACCGTGG...,alt:cg03073402:SNPCENTER:chr19:42927676:C:G:42...,cg03073402,Bertram,LIPE
2,GCGCTCACCTTTGGCCTTGTCTTTTCGCCACCGCCGGCGACCGTGG...,ref:cg03073402:SNPCENTER:chr19:42927676:C:G:42...,cg03073402,Bertram,LIPE
3,TGCCCATTTCCTGATTCTCTCTGTGTCCCCTCAGGCCTCGGCGCTG...,alt:cg03169557:SNPCENTER:chr16:89598950:C:G:89...,cg03169557,Bertram,SPG7
4,TGCCCATTTCCTGATTCTCTCTGTGTCCCCTCAGGCCTCGGCGCTG...,ref:cg03169557:SNPCENTER:chr16:89598950:C:G:89...,cg03169557,Bertram,SPG7
5,CTGGATATACTTACACTAAAAAAAAAATTATTCGTTACTTGTCTGA...,alt:cg05030077:SNPCENTER:chr16:2255199:C:G:225...,cg05030077,Bertram,MLST8
...,...,...,...,...,...
1777,GGAAAGCCCCCGTCTTCCGAGGAGAAGCTCCTCGCTCTCCTCCCAC...,ref:rs965034941:SNPCENTER:chr19:1999195:CCA:C:...,rs965034941,Tanzi,NaN
1778,ACATTTGTGAAGTGATTTTTTAAAACTAAAATTCCACATGCAATTT...,ref:rs983392:PEAKCENTER:chr11:59923508:A:G:599...,rs983392,Pfenning,MS4A6A
1779,ACATTTGTGAAGTGATTTTTTAAAACTAAAATTCCACGTGCAATTT...,alt:rs983392:PEAKCENTER:chr11:59923508:A:G:599...,rs983392,Pfenning,MS4A6A
1780,CAAGACTCCATCTCAAAAAAAAAAGAAGGAAGGAAAGTAAGGAAAG...,ref:rs9912783:PEAKCENTER:chr17:61522705:C:T:61...,rs9912783,Pfenning,CYB561
1781,CAAGACTCCATCTCAAAAAAAAAAGAAGGAAGGAAAGTAAGGAAAG...,alt:rs9912783:PEAKCENTER:chr17:61522705:C:T:61...,rs9912783,Pfenning,CYB561

In [20]:
#!/bin/bash 
source activate keras2-tf27 

get_activation="/jet/home/zihengc/src/cnn_pipeline/scripts/get_activations.py"
model_path="/ocean/projects/bio210062p/zihengc/ad_ml/models"
peak_path_hg38="/ocean/projects/bio210062p/zihengc/ad_ml/expand_peaks_500bp_hg38"
peak_path_mm10="/ocean/projects/bio210062p/zihengc/ad_ml/expand_peaks_500bp_mm10"
save_path="/jet/home/zihengc/ocean_zihengc/ad_ml/prediction/enhancer10kb/"

python "${get_activation}" -model "${model_path}/THP1_LPSIFNG_Calvin.h5" -in_files "${peak_path_hg38}/THP1_LPSIFNG_4hrs.idr.optimal_peak.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/hg38/hg38.fa -out_file "${save_path}/20240801_THP1_LPSIFNG_4hrs.idr.optimal_peak.narrowPeak.validation.withNeg.csv" --write_csv 
python "${get_activation}" -model "${model_path}/THP1_IFNG-model-best.h5" -in_files "${peak_path_hg38}/THP1_IFNG_4hrs.idr.optimal_peak.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/hg38/hg38.fa -out_file "${save_path}/20240801_THP1_IFNG_4hrs.idr.optimal_peak.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/THP1_IFNB-model-best.h5" -in_files "${peak_path_hg38}/THP1_IFNB_4hrs.idr.optimal_peak.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/hg38/hg38.fa -out_file "${save_path}/20240801_THP1_IFNB_4hrs.idr.optimal_peak.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/THP1_Naive-model-best.h5" -in_files "${peak_path_hg38}/THP1_Naive_4hrs.idr.optimal_peak.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/hg38/hg38.fa -out_file "${save_path}/20240801_THP1_Naive_4hrs.idr.optimal_peak.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/HEK293_ATAC_high_depth0729-model-best.h5" -in_files "${peak_path_hg38}/HEK293_ATAC_high_depth.idr.optimal_peak.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/hg38/hg38.fa -out_file "${save_path}/20240801_HEK293_ATAC_high_depth.idr.optimal_peak.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/HEK293T_ATAC-model-best.h5" -in_files "${peak_path_hg38}/HEK293T_ATAC.idr.optimal_peak.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/hg38/hg38.fa -out_file "${save_path}/20240801_HEK293T_ATAC.idr.optimal_peak.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/THP1_monocyte0729-model-best.h5" -in_files "${peak_path_hg38}/THP1_monocytes.idr.optimal_peak.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/hg38/hg38.fa -out_file "${save_path}/20240801_THP1_monocytes.idr.optimal_peak.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/Mouse_Striatum_AgeC-model-best.h5" -in_files "${peak_path_mm10}/Striatum_AgeC_ATAC_out_ppr.IDR0.1.filt.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/mm10/mm10.fa -out_file "${save_path}/20240801_Striatum_AgeC_ATAC_out_ppr.IDR0.1.filt.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/Mouse_Striatum_AgeB-model-best.h5" -in_files "${peak_path_mm10}/Striatum_AgeB_ATAC_out_ppr.IDR0.1.filt.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/mm10/mm10.fa -out_file "${save_path}/20240801_Striatum_AgeB_ATAC_out_ppr.IDR0.1.filt.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/Mouse_Cortex_AgeB-model-best.h5" -in_files "${peak_path_mm10}/Cortex_AgeB_ATAC_out_ppr.IDR0.1.filt.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/mm10/mm10.fa -out_file "${save_path}/20240801_Cortex_AgeB_ATAC_out_ppr.IDR0.1.filt.narrowPeak.validation.withNeg.csv" --write_csv
python "${get_activation}" -model "${model_path}/Mouse_Cortex_AgeC-model-best.h5" -in_files "${peak_path_mm10}/Cortex_AgeC_ATAC_out_ppr.IDR0.1.filt.narrowPeak.validation.withNeg.bed" -in_genome /ocean/projects/bio210062p/zihengc/genome/mm10/mm10.fa -out_file "${save_path}/20240801_Cortex_AgeC_ATAC_out_ppr.IDR0.1.filt.narrowPeak.validation.withNeg.csv" --write_csv

,ZC100-MPRA3-AP1134-26-Striatum_ALT_Barcode_1,ZC100-MPRA3-AP1134-26-Striatum_ALT_Barcode_2,ZC100-MPRA3-AP1134-26-Striatum_ALT_Barcode_3,ZC100-MPRA3-AP1134-26-Striatum_ALT_Barcode_4,ZC100-MPRA3-AP1134-26-Striatum_ALT_Barcode_5,ZC101-MPRA3-AP1134-26-Hippocampus_ALT_Barcode_1,ZC101-MPRA3-AP1134-26-Hippocampus_ALT_Barcode_2,ZC101-MPRA3-AP1134-26-Hippocampus_ALT_Barcode_3,ZC101-MPRA3-AP1134-26-Hippocampus_ALT_Barcode_4,ZC101-MPRA3-AP1134-26-Hippocampus_ALT_Barcode_5,...,ZC97-MPRA3-AP1133-26-Hippocampus_ALT_Barcode_1,ZC97-MPRA3-AP1133-26-Hippocampus_ALT_Barcode_2,ZC97-MPRA3-AP1133-26-Hippocampus_ALT_Barcode_3,ZC97-MPRA3-AP1133-26-Hippocampus_ALT_Barcode_4,ZC97-MPRA3-AP1133-26-Hippocampus_ALT_Barcode_5,ZC99-MPRA3-AP1134-26-Cortex_ALT_Barcode_1,ZC99-MPRA3-AP1134-26-Cortex_ALT_Barcode_2,ZC99-MPRA3-AP1134-26-Cortex_ALT_Barcode_3,ZC99-MPRA3-AP1134-26-Cortex_ALT_Barcode_4,ZC99-MPRA3-AP1134-26-Cortex_ALT_Barcode_5
alt:cg03073402:SNPCENTER:chr19:42927676:C:G:42927563:42927789:42927676,12547.0,23530.0,21870.0,26030.0,22757.0,12547.0,23530.0,21870.0,26030.0,22757.0,...,12547.0,23530.0,21870.0,26030.0,22757.0,12547.0,23530.0,21870.0,26030.0,22757.0
alt:cg03169557:SNPCENTER:chr16:89598950:C:G:89598837:89599063:89598950,27745.0,41175.0,39699.0,47800.0,49737.0,27745.0,41175.0,39699.0,47800.0,49737.0,...,27745.0,41175.0,39699.0,47800.0,49737.0,27745.0,41175.0,39699.0,47800.0,49737.0
alt:cg05030077:SNPCENTER:chr16:2255199:C:G:2255086:2255312:2255199,9694.0,15933.0,15333.0,17294.0,21199.0,9694.0,15933.0,15333.0,17294.0,21199.0,...,9694.0,15933.0,15333.0,17294.0,21199.0,9694.0,15933.0,15333.0,17294.0,21199.0
alt:cg05066959:SNPCENTER:chr8:41519308:C:G:41519195:41519421:41519308,21182.0,23184.0,21866.0,33318.0,33153.0,21182.0,23184.0,21866.0,33318.0,33153.0,...,21182.0,23184.0,21866.0,33318.0,33153.0,21182.0,23184.0,21866.0,33318.0,33153.0
alt:cg05228284:SNPCENTER:chr19:2720847:C:G:2720734:2720960:2720847,6474.0,9696.0,14805.0,14858.0,17019.0,6474.0,9696.0,14805.0,14858.0,17019.0,...,6474.0,9696.0,14805.0,14858.0,17019.0,6474.0,9696.0,14805.0,14858.0,17019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ref:rs9281938:PEAKCENTER:chr6:32576282:T:TA:32576044:32576544:32576294,7145.0,8546.0,11533.0,10474.0,13958.0,7145.0,8546.0,11533.0,10474.0,13958.0,...,7145.0,8546.0,11533.0,10474.0,13958.0,7145.0,8546.0,11533.0,10474.0,13958.0
ref:rs9304646:PEAKCENTER:chr19:44947151:T:A:44946977:44947477:44947227,16567.0,19664.0,21295.0,22974.0,23984.0,16567.0,19664.0,21295.0,22974.0,23984.0,...,16567.0,19664.0,21295.0,22974.0,23984.0,16567.0,19664.0,21295.0,22974.0,23984.0
ref:rs9357546:PEAKCENTER:chr6:47549495:C:T:47549371:47549664:47549511,4928.0,6203.0,11370.0,10082.0,12252.0,4928.0,6203.0,11370.0,10082.0,12252.0,...,4928.0,6203.0,11370.0,10082.0,12252.0,4928.0,6203.0,11370.0,10082.0,12252.0
ref:rs983392:PEAKCENTER:chr11:59923508:A:G:59923333:59923833:59923583,7348.0,10948.0,15933.0,13101.0,11226.0,7348.0,10948.0,15933.0,13101.0,11226.0,...,7348.0,10948.0,15933.0,13101.0,11226.0,7348.0,10948.0,15933.0,13101.0,11226.0
ref:rs9912783:PEAKCENTER:chr17:61522705:C:T:61522574:61522824:61522636,12166.0,25132.0,21002.0,16274.0,16305.0,12166.0,25132.0,21002.0,16274.0,16305.0,...,12166.0,25132.0,21002.0,16274.0,16305.0,12166.0,25132.0,21002.0,16274.0,16305.0