In [1]:
import pandas as pd

In [27]:
def find_overlap_peak(df,df_atac):

    df_haploreg = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/indexing/enhancer_haploregannotatr_ATAC_tss_SNPFunction_20240911.csv',index_col=0)
    df = pd.merge(df,df_haploreg,left_index=True,right_index=True)
    df = df[df['fdr']<=0.05]
    mpra_df = df[['chr','pos_hg38','fdr','logFC','start','end','summit'
]]


    df_atac = df_atac.rename({"Unnamed: 0":"peak"},axis=1)
    atac_df = df_atac[df_atac['padj']<=0.05]
    # Parse ATAC peak column to chr, start, end
    atac_df[['chr', 'start_end']] = atac_df['peak'].str.split(':', expand=True)
    atac_df[['start', 'end']] = atac_df['start_end'].str.split('-', expand=True)
    atac_df['start'] = atac_df['start'].astype(int)
    atac_df['end'] = atac_df['end'].astype(int)
    atac_df.drop(columns=['start_end'], inplace=True)

    # Creating a list to store overlapping information with the updated requirements
    overlapping_info_with_index = []

    # Iterate over MPRA dataframe and check for overlaps with updated information
    for index, mpra_row in mpra_df.iterrows():
        chr_match = atac_df[atac_df['chr'] == mpra_row['chr']]
        overlap = chr_match[(chr_match['start'] <= mpra_row['pos_hg38']) & (chr_match['end'] >= mpra_row['pos_hg38'])]
        
        if not overlap.empty:
            for _, atac_row in overlap.iterrows():
                overlapping_info_with_index.append({
                    "mpra_index": index,
                    "chr": mpra_row['chr'],
                    "pos_hg38": mpra_row['pos_hg38'],
                    "mpra_logFC": mpra_row['logFC'],
                    "atac_peak": atac_row['peak'],
                    "atac_log2FoldChange": atac_row['log2FoldChange'],
                    "atac_padj": atac_row['padj'],
                    'mpra_peak':str(mpra_row['start'])+':'+str(mpra_row['end'])+':'+str(mpra_row['summit']),
                })

    # Convert overlapping information to DataFrame
    overlapping_table_with_index_df = pd.DataFrame(overlapping_info_with_index)

    # Convert overlapping information to DataFrame
    return overlapping_table_with_index_df

In [ ]:
df = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/enhancer_activities_differential/20240626_comparative_THP1_LPSIFNGvsNaive_DifferentialEnhancer.csv' ,index_col=0)
df_atac = pd.read_csv('/media/zihengc/T7/atac/differential_analysis/novaseq2/data/bam/THP1_LPS4_IFNB4_IFNG4_NAIVE/LPSIFNG4_vs_Naive_IHW.csv' )
lps_naive = find_overlap_peak(df,df_atac)
lps_naive

/tmp/ipykernel_160526/2580135720.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['chr', 'start_end']] = atac_df['peak'].str.split(':', expand=True)
/tmp/ipykernel_160526/2580135720.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['chr', 'start_end']] = atac_df['peak'].str.split(':', expand=True)
/tmp/ipykernel_160526/2580135720.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['start', 'end']] = atac_df['start_end'].str.split('-', expand=True)
/tmp/ipykernel_160526/2580135720.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['start', 'end']] = atac_df['start_end'].str.split('-', expand=True)
/tmp/ipykernel_160526/2580135720.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df['start'] = atac_df['start'].astype(int)
/tmp/ipykernel_160526/2580135720.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df['end'] = atac_df['end'].astype(int)
/tmp/ipykernel_160526/2580135720.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df.drop(columns=['start_end'], inplace=True)

,mpra_index,chr,pos_hg38,mpra_logFC,atac_peak,atac_log2FoldChange,atac_padj,mpra_peak
0,alt:rs146215324:PEAKCENTER:chr17:39245204:G:A:...,chr17,39245204,0.136618,chr17:39244015-39245248,1.132560,8.555199e-04,39244646.0:39245204.0:39245154
1,alt:rs17854357:SNPCENTER:chr11:65834089:G:C:65...,chr11,65834089,0.182289,chr11:65833319-65834376,1.181822,7.420424e-05,65833162.0:65834810.0:65833986
2,alt:rs2927438:PEAKCENTER:chr19:44738850:G:A:44...,chr19,44738850,-0.152081,chr19:44738787-44739216,1.298639,5.797640e-05,44738683.0:44739183.0:44738933
3,alt:rs3809715:PEAKCENTER:chr17:75271453:A:C:75...,chr17,75271453,0.137339,chr17:75270275-75271944,0.745113,6.997551e-03,75270241.0:75271699.0:75271532
4,alt:rs3826327:PEAKCENTER:chr17:75271437:C:A:75...,chr17,75271437,-0.447705,chr17:75270275-75271944,0.745113,6.997551e-03,75270300.0:75271666.0:75271337
5,alt:rs3826327:PEAKCENTER:chr17:75271437:C:A:75...,chr17,75271437,0.146847,chr17:75270275-75271944,0.745113,6.997551e-03,75270830.0:75271630.0:75271541
6,alt:rs3826327:PEAKCENTER:chr17:75271437:C:T:75...,chr17,75271437,-0.420001,chr17:75270275-75271944,0.745113,6.997551e-03,75270300.0:75271666.0:75271337
7,alt:rs3826327:PEAKCENTER:chr17:75271437:C:T:75...,chr17,75271437,0.135011,chr17:75270275-75271944,0.745113,6.997551e-03,75270830.0:75271630.0:75271541
8,alt:rs6464547:PEAKCENTER:chr7:143386568:A:C:14...,chr7,143386568,-0.140777,chr7:143386205-143386717,-1.346580,1.623382e-07,143386295.0:143386795.0:143386545
9,alt:rs9270906:PEAKCENTER:chr6:32572079:T:C:325...,chr6,32604302,-0.176304,chr6:32603742-32604939,0.722359,9.406760e-03,32571733.0:32572743.0:32572143
10,alt:rs9270907:PEAKCENTER:chr6:32572082:C:T:325...,chr6,32604305,-0.207899,chr6:32603742-32604939,0.722359,9.406760e-03,32571733.0:32572743.0:32572143
11,alt:rs9270913:PEAKCENTER:chr6:32572229:A:G:325...,chr6,32604452,-0.172624,chr6:32603742-32604939,0.722359,9.406760e-03,32571733.0:32572743.0:32572301
12,alt:rs9270914:PEAKCENTER:chr6:32572249:A:T:325...,chr6,32604472,-0.155553,chr6:32603742-32604939,0.722359,9.406760e-03,32571733.0:32572743.0:32572301
13,alt:rs9270915:PEAKCENTER:chr6:32572290:G:A:325...,chr6,32604513,-0.153920,chr6:32603742-32604939,0.722359,9.406760e-03,32571733.0:32572743.0:32572301
14,alt:rs9270920:PEAKCENTER:chr6:32572322:C:T:325...,chr6,32604545,-0.240200,chr6:32603742-32604939,0.722359,9.406760e-03,32571733.0:32572743.0:32572301
15,alt:rs9271150:PEAKCENTER:chr6:32577470:T:G:325...,chr6,32609693,-0.241961,chr6:32609619-32610391,0.684757,8.494440e-03,32577256.0:32578131.0:32577468
16,alt:rs9271163:PEAKCENTER:chr6:32577733:C:T:325...,chr6,32609956,-0.139266,chr6:32609619-32610391,0.684757,8.494440e-03,32577256.0:32578131.0:32577812
17,ref:rs12703526:PEAKCENTER:chr7:143107588:G:T:1...,chr7,143410495,-0.149077,chr7:143410429-143411046,-1.068106,2.351609e-03,143107527.0:143108024.0:143107693
18,ref:rs12703526:SNPCENTER:chr7:143107588:G:T:14...,chr7,143410495,-0.222515,chr7:143410429-143411046,-1.068106,2.351609e-03,143107527.0:143108024.0:143107693
19,ref:rs3826327:PEAKCENTER:chr17:75271437:C:A:75...,chr17,75271437,-0.400437,chr17:75270275-75271944,0.745113,6.997551e-03,75270300.0:75271666.0:75271337
20,ref:rs9270893:PEAKCENTER:chr6:32571845:C:T:325...,chr6,32604068,-0.200531,chr6:32603742-32604939,0.722359,9.406760e-03,32571672.0:32572694.0:32571880
21,ref:rs9270906:PEAKCENTER:chr6:32572079:T:C:325...,chr6,32604447,-0.161882,chr6:32603742-32604939,0.722359,9.406760e-03,32571733.0:32572743.0:32572143
22,ref:rs9270912:PEAKCENTER:chr6:32572224:A:G:325...,chr6,32604545,-0.218272,chr6:32603742-32604939,0.722359,9.406760e-03,32571733.0:32572743.0:32572301
23,ref:rs9271163:PEAKCENTER:chr6:32577733:C:T:325...,chr6,32610112,-0.153998,chr6:32609619-32610391,0.684757,8.494440e-03,32577256.0:32578131.0:32577812

In [16]:
df = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/enhancer_activities_differential/20240626_comparative_THP1_IFNGvsNaive_DifferentialEnhancer.csv' ,index_col=0)
df_atac = pd.read_csv('/media/zihengc/T7/atac/differential_analysis/novaseq2/data/bam/THP1_LPS4_IFNB4_IFNG4_NAIVE/IFNG4_vs_Naive_IHW.csv' )
ifng_naive = find_overlap_peak(df,df_atac)
ifng_naive

/tmp/ipykernel_160526/1635624981.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['chr', 'start_end']] = atac_df['peak'].str.split(':', expand=True)
/tmp/ipykernel_160526/1635624981.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['chr', 'start_end']] = atac_df['peak'].str.split(':', expand=True)
/tmp/ipykernel_160526/1635624981.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['start', 'end']] = atac_df['start_end'].str.split('-', expand=True)
/tmp/ipykernel_160526/1635624981.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['start', 'end']] = atac_df['start_end'].str.split('-', expand=True)
/tmp/ipykernel_160526/1635624981.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df['start'] = atac_df['start'].astype(int)
/tmp/ipykernel_160526/1635624981.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df['end'] = atac_df['end'].astype(int)
/tmp/ipykernel_160526/1635624981.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df.drop(columns=['start_end'], inplace=True)

Empty DataFrame
Columns: []
Index: []

In [17]:
df = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/enhancer_activities_differential/20240626_comparative_THP1_IFNBvsNaive_DifferentialEnhancer.csv' ,index_col=0)
df_atac = pd.read_csv('/media/zihengc/T7/atac/differential_analysis/novaseq2/data/bam/THP1_LPS4_IFNB4_IFNG4_NAIVE/IFNB4_vs_Naive_IHW.csv' )
ifnb_naive = find_overlap_peak(df,df_atac)
ifnb_naive

/tmp/ipykernel_160526/1635624981.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['chr', 'start_end']] = atac_df['peak'].str.split(':', expand=True)
/tmp/ipykernel_160526/1635624981.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['chr', 'start_end']] = atac_df['peak'].str.split(':', expand=True)
/tmp/ipykernel_160526/1635624981.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['start', 'end']] = atac_df['start_end'].str.split('-', expand=True)
/tmp/ipykernel_160526/1635624981.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df[['start', 'end']] = atac_df['start_end'].str.split('-', expand=True)
/tmp/ipykernel_160526/1635624981.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df['start'] = atac_df['start'].astype(int)
/tmp/ipykernel_160526/1635624981.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df['end'] = atac_df['end'].astype(int)
/tmp/ipykernel_160526/1635624981.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  atac_df.drop(columns=['start_end'], inplace=True)

Empty DataFrame
Columns: []
Index: []