In [3]:
import pandas as pd
df_index = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/indexing/SNP_haploregannotatr_ATAC_tss_SNPFunction_20240911.csv',index_col=0)
df_index

,Type,RSID,Contributor,nearest_gene,rsID,chr_number,pos_hg38,r2,D',is_query_snp,...,Alasoo_Macrophage_ATAC_hg38.bed,Corces_Microglia_sgATAC_hg38.idr.optimal.narrowPeak,HEK293T_ATAC.idr.conservative_peak.narrowPeak,B_cells_hg38.bed,dendritic_hg38.bed,basophil_hg38.bed,progen_hg38.bed,GC_content,distance_to_tss,SNP_Function
index,,,,,,,,,,,,,,,,,,,,,
alt:cg03073402:SNPCENTER:chr19:42927676:C:G:42927563:42927789:42927676,AD,cg03073402,Bertram,LIPE,cg03073402,19,42423524,NaN,NaN,NaN,...,1,1,1,1,1,1,1,68.281938,1547,Ubiquitous
alt:cg03169557:SNPCENTER:chr16:89598950:C:G:89598837:89599063:89598950,AD,cg03169557,Bertram,SPG7,cg03169557,16,89532542,NaN,NaN,NaN,...,0,0,0,0,0,0,0,62.114537,-28082,Low ATAC
alt:cg05030077:SNPCENTER:chr16:2255199:C:G:2255086:2255312:2255199,AD,cg05030077,Bertram,MLST8,cg05030077,16,2205198,NaN,NaN,NaN,...,1,1,0,1,1,1,1,56.828194,-950,Ubiquitous
alt:cg05066959:SNPCENTER:chr8:41519308:C:G:41519195:41519421:41519308,AD,cg05066959,Bertram,ANK1,cg05066959,8,41661790,NaN,NaN,NaN,...,0,1,0,0,0,0,0,60.792952,-799,Low ATAC
alt:cg05228284:SNPCENTER:chr19:2720847:C:G:2720734:2720960:2720847,AD,cg05228284,Bertram,DIRAS1,cg05228284,19,2720849,NaN,NaN,NaN,...,0,0,0,0,1,0,0,73.568282,523,Low ATAC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
alt:rs9478143:PEAKCENTER:chr6:150862035:A:G:150861632:150862271:150862051,AD,rs9478143,Tanzi,MTHFD1L,rs9478143,6,150862035,1.0,1.0,1.0,...,1,1,0,1,1,0,1,46.255507,3644,Immune
alt:rs953471:PEAKCENTER:chr9:124221903:G:A:124221758:124221963:124221854,AD,rs953471,Tanzi,NEK6,rs953471,9,124221903,1.0,1.0,1.0,...,0,0,0,0,1,1,1,48.458150,35703,Low ATAC
alt:rs965034941:SNPCENTER:chr19:1999195:CCA:C:1999082:1999308:1999195,AD,rs965034941,Tanzi,BTBD2,rs965034941,19,1999195,NaN,NaN,NaN,...,0,0,0,0,1,0,1,67.111111,4386,Low ATAC
alt:rs983392:PEAKCENTER:chr11:59923508:A:G:59923333:59923833:59923583,AD,rs983392,Pfenning,MS4A6A,rs983392,11,60156035,1.0,1.0,1.0,...,0,0,0,0,1,1,1,35.682819,4787,Low ATAC
alt:rs9912783:PEAKCENTER:chr17:61522705:C:T:61522574:61522824:61522636,AD,rs9912783,Pfenning,CYB561,rs9912783,17,63445344,1.0,1.0,1.0,...,0,0,0,0,0,0,0,47.577093,1010,Low ATAC

In [5]:
df_refalt = pd.read_csv('indexing/ALT_REF_LookUpTable_filtered_amended_alleleOnly_20240605.csv')
df_refalt

,0,1
0,alt:rs9912783:PEAKCENTER:chr17:61522705:C:T:61...,ref:rs9912783:PEAKCENTER:chr17:61522705:C:T:61...
1,alt:rs983392:PEAKCENTER:chr11:59923508:A:G:599...,ref:rs983392:PEAKCENTER:chr11:59923508:A:G:599...
2,alt:rs965034941:SNPCENTER:chr19:1999195:CCA:C:...,ref:rs965034941:SNPCENTER:chr19:1999195:CCA:C:...
3,alt:rs953471:PEAKCENTER:chr9:124221903:G:A:124...,ref:rs545732955:PEAKCENTER:chr9:124221781:A:C:...
4,alt:rs9478143:PEAKCENTER:chr6:150862035:A:G:15...,ref:rs113543131:PEAKCENTER:chr6:150862117:C:T:...
...,...,...
850,alt:cg05066959:SNPCENTER:chr8:41519308:C:G:415...,ref:cg05066959:SNPCENTER:chr8:41519308:C:G:415...
851,alt:cg05030077:SNPCENTER:chr16:2255199:C:G:225...,ref:cg05030077:SNPCENTER:chr16:2255199:C:G:225...
852,alt:cg03169557:SNPCENTER:chr16:89598950:C:G:89...,ref:cg03169557:SNPCENTER:chr16:89598950:C:G:89...
853,alt:cg03073402:SNPCENTER:chr19:42927676:C:G:42...,ref:cg03073402:SNPCENTER:chr19:42927676:C:G:42...
854,alt:rs1198397268:SNPCENTER:chr19:1999196:CAG:C...,ref:rs965034941:SNPCENTER:chr19:1999195:CCA:C:...

In [9]:
df_alt = df_index.loc[df_refalt['0']].copy()

In [20]:
df_ref = df_index.loc[df_refalt['0']].copy()
df_ref.index = df_refalt['1']
df_ref = df_ref.reset_index().drop_duplicates(subset='1').set_index('1')

In [22]:
df_enhancer = pd.concat([df_alt,df_ref])

In [25]:
df_enhancer.to_csv("indexing/enhancer_haploregannotatr_ATAC_tss_SNPFunction_20240911.csv")