In [58]:
import pandas as pd

# Load the table containing "RSID" column
rsid_table = pd.read_csv('indexing/SNP_haploregannotatr_ATAC_tss_SNPFunction_spliceai_bayesianML_20240919.csv',index_col=0)
unique_rsids = set(rsid_table['RSID'].unique())  # Extract unique RSIDs and store in a set

# Initialize an empty list to store matching rows
matching_rows = []

# Define a function to process each chunk of the TSV file
def filter_chunk(chunk):
    # Filter rows in the chunk where the variant_id matches one of the RSIDs
    return chunk[chunk['variant_id'].isin(unique_rsids)]

# Load the large TSV file in chunks
chunk_size = 10**6  # Adjust chunk size if needed based on memory
tsv_file_path = '/media/zihengc/T7/mpra/resources/Bellenguez/GCST90027158_buildGRCh38.tsv'

# Iterate over chunks of the TSV file
for chunk in pd.read_csv(tsv_file_path, sep='\t', chunksize=chunk_size):
    matching_rows.append(filter_chunk(chunk))

# Concatenate all matching rows into a final DataFrame
result_df = pd.concat(matching_rows)

# Save the result if needed
result_df.to_csv('indexing/20241021_SNPs_GWAS_match.csv', index=False)

In [9]:
'''
RSID = rsid_table[(rsid_table['Contributor']!="Tanzi")&(rsid_table['Contributor']!="Hide")]['RSID'].tolist()
RSID = rsid_table[rsid_table['EUR']<=0.01]['RSID'].tolist()
result_df[result_df['variant_id'].isin(RSID)].sort_values('p_value')
'''

In [55]:
rsid_table = pd.merge(rsid_table, 
                      result_df[['variant_id', 'p_value']], 
                      left_on='RSID', 
                      right_on='variant_id', 
                      how='left') \
               .rename({'p_value': 'Bellenguez_p_value'}, axis=1) \
               .drop_duplicates('RSID')
import numpy as np
rsid_table['Bellenguez_p_value_negLog10'] = -np.log10(rsid_table["Bellenguez_p_value"])
rsid_table.to_csv('indexing/20241021_SNPs_GWAS_match_pvalue_uniqueSNPs.csv', index=False)
rsid_table

In [60]:
rsid_table = pd.merge(rsid_table, 
                      result_df[['variant_id', 'p_value']], 
                      left_on='RSID', 
                      right_on='variant_id', 
                      how='left') \
               .rename({'p_value': 'Bellenguez_p_value'}, axis=1)
import numpy as np
rsid_table['Bellenguez_p_value_negLog10'] = -np.log10(rsid_table["Bellenguez_p_value"])
rsid_table.to_csv('indexing/SNP_haploregannotatr_ATAC_tss_SNPFunction_spliceai_bayesianML_Bellenguez_202401021.csv', index=False)
rsid_table

,Type,RSID,Contributor,nearest_gene,rsID,chr_number,pos_hg38,r2,D',is_query_snp,...,ML_majormino_logFC_Mouse_Striatum_AgeB,ML_majormino_logFC_Mouse_Striatum_AgeC,ML_majormino_logFC_THP1_IFNB-Calvin_20,ML_majormino_logFC_THP1_IFNG-Calvin_20,ML_majormino_logFC_THP1_LPSIFNG-Calvin,ML_majormino_logFC_THP1_Naive-Calvin_2,ML_majormino_logFC_THP1_monocyte0729_2,variant_id,Bellenguez_p_value,Bellenguez_p_value_negLog10
0,AD,cg03073402,Bertram,LIPE,cg03073402,19,42423524,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.12,NaN,NaN,NaN,NaN
1,AD,cg03169557,Bertram,SPG7,cg03169557,16,89532542,NaN,NaN,NaN,...,0.12,0.17,0.11,0.13,NaN,0.11,NaN,NaN,NaN,NaN
2,AD,cg05030077,Bertram,MLST8,cg05030077,16,2205198,NaN,NaN,NaN,...,NaN,NaN,0.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AD,cg05066959,Bertram,ANK1,cg05066959,8,41661790,NaN,NaN,NaN,...,0.18,0.23,NaN,NaN,NaN,NaN,0.51,NaN,NaN,NaN
4,AD,cg05228284,Bertram,DIRAS1,cg05228284,19,2720849,NaN,NaN,NaN,...,0.21,0.21,0.74,0.52,0.86,NaN,0.25,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,AD,rs9478143,Tanzi,MTHFD1L,rs9478143,6,150862035,1.0,1.0,1.0,...,-0.14,-0.14,NaN,NaN,NaN,NaN,NaN,rs9478143,9.793000e-01,0.009084
851,AD,rs953471,Tanzi,NEK6,rs953471,9,124221903,1.0,1.0,1.0,...,0.19,0.17,NaN,0.11,0.20,NaN,NaN,rs953471,6.716000e-01,0.172889
852,AD,rs965034941,Tanzi,BTBD2,rs965034941,19,1999195,NaN,NaN,NaN,...,0.10,NaN,NaN,NaN,0.15,-0.15,NaN,NaN,NaN,NaN
853,AD,rs983392,Pfenning,MS4A6A,rs983392,11,60156035,1.0,1.0,1.0,...,NaN,-0.10,NaN,NaN,NaN,NaN,NaN,rs983392,2.257000e-17,16.646468
854,AD,rs9912783,Pfenning,CYB561,rs9912783,17,63445344,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,-0.10,NaN,NaN,rs9912783,1.692000e-03,2.771600

In [64]:
len(rsid_table[rsid_table['nearest_gene']=='HLA-DRB1']['rsID'].unique())

61

In [3]:
df_dmi = pd.read_csv('/media/zihengc/T7/mpra/MPRA_design/Dmitry/All_SNPs.xlsx - Dmitry 148.csv')

,chr,pos,startsnp,endsnp,nSNPs,W,var,Z,p,nearestgene,Cell_type
0,8,133356958,8:133356958:T:A,8:133357141:C:T,3,-2.178,0.282,-4.105,0.000041,NDRG1,Monocytes
1,6,43454798,6:43454798:G:A,6:43454960:C:T,2,-1.965,0.229,-4.102,0.000041,DLK2,Monocytes
2,19,33879678,19:33879678:C:T,19:33880050:C:T,3,1.909,0.221,4.065,0.000048,KCTD15,Monocytes
3,17,75271426,17:75271426:G:C,17:75271848:G:A,9,4.659,1.361,3.993,0.000065,MIF4GD,Monocytes
4,17,75301032,17:75301032:C:A,17:75302054:T:G,12,7.078,3.339,3.873,0.000107,SLC25A19,Monocytes
...,...,...,...,...,...,...,...,...,...,...,...
68,5,101299295,5:101299295:G:A,5:101299815:A:T,10,6.420,3.329,3.519,0.000433,ST8SIA4,Neuron
69,7,128706344,7:128706344:C:T,7:128706354:T:C,2,-1.519,0.188,-3.501,0.000463,FAM71F1,Neuron
70,6,119110489,6:119110489:G:T,6:119111058:T:C,5,4.494,1.650,3.499,0.000467,FAM184A,Neuron
71,19,12736900,19:12736900:C:T,19:12737183:G:A,5,-2.635,0.569,-3.494,0.000476,GET3,Neuron
72,4,14024908,4:14024908:A:G,4:14025298:C:T,5,-3.470,0.993,-3.483,0.000497,BOD1L.1,Neuron