In [1]:
import pandas as pd
df_mad = pd.DataFrame()
for folder in ['Brain_byAllele',"HMC3_byAllele","HEK293T_byAllele","THP1Monocyte_byAllele", "THP1Macrophage_byAllele"]:
    df = pd.read_csv(f"./enhancer_activities/{folder}/20240105_MPRA3_MAD_mergedREF.csv",index_col=0)
    df_mad[folder] = df["mad.score"]

In [2]:
df_mad

,Brain_byAllele,HMC3_byAllele,HEK293T_byAllele,THP1Monocyte_byAllele,THP1Macrophage_byAllele
ARP.Control.CS6000023125_Raegyp2_NW_015494788.1,5.462031,-0.859787,-1.289615,-0.177961,-0.224184
ARP.Control.CS6000035558_panTro4_chr12,3.688532,1.658341,0.140065,1.229352,-0.016309
ARP.Control.CS6000065474_rheMac8_chr20,1.390701,0.514557,-0.881638,-0.634362,-0.709017
ARP.Control.CS6000076312_mm10_chr18,3.712554,1.266702,0.979057,-0.635054,-0.598127
ARP.Control.CS6000151238_taeGut2_chr19,3.087833,0.881976,2.414531,1.354064,0.003297
...,...,...,...,...,...
rs9271090:chr6:32576247:T:C:32576044:32576544:32576294_motifdisrupt,2.469430,4.809463,-1.014771,2.763540,1.976896
rs9271170:chr6:32577889:T:C:32577256:32578131:32577812_motifdisrupt,-0.319341,7.400351,7.186328,4.154032,2.466694
rs9271174:chr6:32578040:C:G:32577256:32578131:32578057_motifdisrupt,0.458248,1.622326,-1.295673,0.107391,0.112632
rs9304646:chr19:44947151:T:A:44946977:44947477:44947227_motifdisrupt,-2.066600,6.069277,0.597546,1.720890,1.859261
rs9478143:chr6:150862035:A:G:150861632:150862271:150862051_motifdisrupt,-1.415837,2.822297,0.709661,0.055172,1.064163

In [3]:
df_rank = df_mad.rank(method='average')

negative = ['ARP.Control.Nguyen_neg_T03000001872',
       'ARP.Control.Nguyen_neg_T03000002350',
       'ARP.Control.Nguyen_neg_T03000006478',
       'ARP.Control.Nguyen_neg_T03000008079',
       'ARP.Control.Nguyen_neg_T03000009050',
       'ARP.Control.Nguyen_neg_T03000009840',
       'ARP.Control.Nguyen_neg_T03000009843',
       'ARP.Control.Nguyen_neg_T03000010893']

df_rank = df_rank[df_rank.index.isin(negative)]

df_rank_rerank = df_rank.rank(method='average')
df_rank_rerank

,Brain_byAllele,HMC3_byAllele,HEK293T_byAllele,THP1Monocyte_byAllele,THP1Macrophage_byAllele
ARP.Control.Nguyen_neg_T03000001872,5.0,1.0,1.0,1.0,2.0
ARP.Control.Nguyen_neg_T03000002350,4.0,3.0,5.0,6.0,6.0
ARP.Control.Nguyen_neg_T03000006478,3.0,5.0,4.0,3.0,3.0
ARP.Control.Nguyen_neg_T03000008079,8.0,2.0,2.0,8.0,8.0
ARP.Control.Nguyen_neg_T03000009050,6.0,8.0,8.0,7.0,7.0
ARP.Control.Nguyen_neg_T03000009840,2.0,7.0,3.0,5.0,5.0
ARP.Control.Nguyen_neg_T03000009843,1.0,4.0,6.0,2.0,1.0
ARP.Control.Nguyen_neg_T03000010893,7.0,6.0,7.0,4.0,4.0

In [4]:
df_rank

,Brain_byAllele,HMC3_byAllele,HEK293T_byAllele,THP1Monocyte_byAllele,THP1Macrophage_byAllele
ARP.Control.Nguyen_neg_T03000001872,901.0,6.0,319.0,113.0,39.0
ARP.Control.Nguyen_neg_T03000002350,773.0,15.0,499.0,400.0,207.0
ARP.Control.Nguyen_neg_T03000006478,684.0,44.0,368.0,174.0,90.0
ARP.Control.Nguyen_neg_T03000008079,1010.0,9.0,335.0,572.0,523.0
ARP.Control.Nguyen_neg_T03000009050,984.0,171.0,870.0,470.0,374.0
ARP.Control.Nguyen_neg_T03000009840,575.0,93.0,364.0,282.0,186.0
ARP.Control.Nguyen_neg_T03000009843,400.0,32.0,545.0,167.0,21.0
ARP.Control.Nguyen_neg_T03000010893,990.0,65.0,817.0,181.0,110.0

# Three negatives chosen
ARP.Control.Nguyen_neg_T03000001872  
ARP.Control.Nguyen_neg_T03000006478 
ARP.Control.Nguyen_neg_T03000009840  
ARP.Control.Nguyen_neg_T03000009843

In [5]:
import pandas as pd
df_MPRA = pd.read_csv('/media/zihengc/T7/mpra3_lib_analysis/indexing/MPRA3_Contributor_20231108_unique_GeneName_BarcodeEnhancerPair.csv',index_col=0)
negative_chosen = [
    'ARP.Control.Nguyen_neg_T03000001872',
'ARP.Control.Nguyen_neg_T03000006478',
'ARP.Control.Nguyen_neg_T03000009840',
'ARP.Control.Nguyen_neg_T03000009843']

df_MPRA[df_MPRA["enhancer_id"].isin(negative_chosen)].drop_duplicates("enhancer_id")[['enhancer_id','enhancer_seq']].to_csv("negative_chosen.csv",index=False)

In [55]:
len('TGTAGATTACAACAACTCCGTTTGTCTTTACTCTTTCGGCTCCGTTTTATTTTCACGACGGGTTACGATTGGTCTTCCTCCGATCCCGCCGCCCTCTCTGGTAGTCGTCGTAATAAAACC')

120